### ISSUE TITLE
Implement system `alalc-hin-deva-latn-1997` (ALA-LC Romanization Table -- Hindi (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#103]
This issue is to implement the transliteration system of alalc-hin-deva-latn-1997.

This system is referred in the GeoNames database as `hin_Deva2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Hindi (1997)'.

 Tests should rely on the data extracted for the `hin_Deva2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
@ronaldtse this should be done by https://github.com/interscript/interscript/pull/369 . which is merged already.

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
