### ISSUE TITLE
Implement system `alalc-kat-geok-latn-1997` (ALA-LC Romanization Table -- Georgian (1997) (Khutsuri)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#113]
This issue is to implement the transliteration system of alalc-kat-geok-latn-1997.

This system is referred in the GeoNames database as `kat_Geor2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Georgian (1997) (Khutsuri)'.

 Tests should rely on the data extracted for the `kat_Geor2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by antonsviridenko** [comment]
Khutsuri is an old Georgian alphabet, not used in modern writing, there is no any sample written in Khutsuri in the GeoNames db. It's active usage stopped around XI century.

Some Unicode samples I was able to find:

http://titus.uni-frankfurt.de/unicode/samples/geobeisp.htm#bolnisi
http://titus.uni-frankfurt.de/texte/etca/cauc/ageo/nt/ntkpl/ntkpl.htm

**Comment by antonsviridenko** [comment]
`Ⴤ - X ⴤ  - x` here in the PDF Latin character 'X' has dot below (underdot), but it is not preserved during copy-paste, and looks like there is no such precomposed character 'latin character X with dot below', trying to figure out how to type it properly :)

**Comment by ronaldtse** [comment]
@antonsviridenko for "X with dot below" (X̣), you would do:
`\u0058\u0323` which is "X" (0058) followed by ["Combining Dot Below" (0323)](https://www.compart.com/en/unicode/U+0323).

You can see how it looks like here:
https://www.branah.com/unicode-converter

**Comment by antonsviridenko** [comment]
ok, I was able to type it, looks like Vim editor is unable to display underdots (at least on my system with my configuration)

**Comment by antonsviridenko** [comment]
Another issue that I've noticed: some fonts display Georgian letters from "Mtavruli" instead of Khutsuri capital letters,
![geok_verdana_monospace](https://user-images.githubusercontent.com/2234049/75574727-3d586500-5a78-11ea-994b-983a2c52f099.png)

Left one is displayed using font Verdana, right one - Monospace. Correct version is on the left.

Possible reasons are more or less described here
https://www.unicode.org/wg2/docs/n4707-georgian.pdf

**Comment by antonsviridenko** [comment]
https://github.com/riboseinc/interscript/pull/260 is ready

**Comment by ronaldtse** [comment]
Done in #260
