### ISSUE TITLE
Implement system `ggg-kat-geor-latn-2002` (Georgian State Department of Geodesy and Cartography 2002 System

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#115]
This issue is to implement the transliteration system of ggg-kat-geor-latn-2002.

This system is referred in the GeoNames database as `kat_Geor2Latn_GGG_2002`, with the system title 'Georgian State Department of Geodesy and Cartography 2002 System'.

 Tests should rely on the data extracted for the `kat_Geor2Latn_GGG_2002` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Data provided here:
[kat_Geor2Latn_GGG_2002.csv.zip](https://github.com/riboseinc/interoperable-transliteration/files/4143786/kat_Geor2Latn_GGG_2002.csv.zip)

**Comment by ronaldtse** [comment]
Spec: https://transliteration.eki.ee/pdf/Georgian.pdf

**Comment by ronaldtse** [comment]
@antonsviridenko could you have a look at this? You can see existing maps under the `maps/` folder to see samples. Thanks!

**Comment by antonsviridenko** [comment]
ok

**Comment by ronaldtse** [comment]
Thanks @antonsviridenko ! Let me know if you have any questions...

**Comment by antonsviridenko** [comment]
@ronaldtse I have a question about how to handle capitalization. There is no case in Georgian, so either Latin output of transliteration should be always in lower case, or every output word should be capitalized if expected that input is always consists of proper names (i.e. geographical locations, city and village names, etc).

Like for example 北京 is transliterated as "Beijing", not "beijing" because it is known to the human that it is a proper name, name of the city, but the script cannot handle that automatically.

**Comment by ronaldtse** [comment]
@antonsviridenko I see! In this case let's always have Latin output always be in lower case.

In the future, we could use the following option to keep output title case (configurable when calling transliteration):

e.g.
https://github.com/riboseinc/interoperable-transliteration/blob/8c63b39ae3556abd2660372ff51ff4fa7402ec38/maps/hk-yue-Han-Latn-govt.yaml#L60

The capitalization of proper names will require context-sensitive parsing which will require more intelligence, and will be something for the future.

**Comment by antonsviridenko** [comment]
W hat could be wrong here? Probably some sample text in Georgian should be added too?

>   1) Interscript maps/ggg-kat-geor-latn-2002.yaml system test for {"source"=>"ბაყაყი"}
>      Failure/Error: expect(result).to eq(test["expected"])
> 
>        expected: nil
>             got: "baq’aq’i"

**Comment by ronaldtse** [comment]
@antonsviridenko you're right, some tests should be added here. Could you help add some tests that are illustrative of the scheme / edge cases, such as from kat_Geor2Latn_GGG_2002.csv ? Thanks!
