### ISSUE TITLE
Implement system `alalc-kor-hang-latn-1997` (ALA-LC Romanization Table -- Korean (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#120]
This issue is to implement the transliteration system of alalc-kor-hang-latn-1997.

This system is referred in the GeoNames database as `kor_Hang2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Korean (1997)'.

 Tests should rely on the data extracted for the `kor_Hang2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by chaaklau** [comment]
The 1997 edition is not available online. According to the 2009 edition on the ALA-LC website (https://www.loc.gov/catdir/cpso/romanization/korean.pdf), they follow McCune-Reischauer System, which has been implemented here: #123 

> 1. 	General Practice
> The Library of Congress will continue to follow the McCune-Reischauer system
> to romanize Korean with the exceptions noted in this document. See:
> Romanization of the Korean Language: Based upon its Phonetic Structure by
> G.M. McCune and E.O. Reischauer ([S.l.: s.n., 1939?), reprinted from the
> Transactions of the Korea Branch of the Royal Asiatic Society. Full text of the
> original document is available online from the National Library of Australia Web
> site: http://www.nla.gov.au/librariesaustralia/cjk/download/ras_1939.pdf

**Comment by ronaldtse** [comment]
@chaaklau all ALA-LC 1997 systems can be found here: http://catdir.loc.gov/catdir/cpso/roman.html

**Comment by chaaklau** [comment]
`kor_Hang2Latn_ALA_1997.csv` in https://github.com/riboseinc/geonames-transliteration-data is empty.

**Comment by ronaldtse** [comment]
If it's the same, we can use this option to indicate extension (inheritance) of the rules of another system:
https://github.com/riboseinc/interoperable-transliteration/blob/b3c0cd26be924500e6481608b947081df055c2cb/lib/interscript/mapping.rb#L86

**Comment by chaaklau** [comment]
> If it's the same, we can use this option to indicate extension (inheritance) of the rules of another system:

The `extend` option only copies the character mappings but not the rules and postrules.
https://github.com/riboseinc/interoperable-transliteration/blob/b3c0cd26be924500e6481608b947081df055c2cb/lib/interscript/mapping.rb#L88-L91

Perhaps we can add a separate option `inherit` for this purpose?

**Comment by ronaldtse** [comment]
I wonder if "extend" should just be "inherit", or we should separate "extend" and "inherit"...?

**Comment by ronaldtse** [comment]
The only line in GeoNames that uses this system is this:

```sql
INSERT INTO "main"."" ("RC", "UFI", "UNI", "LAT", "LONG", "DMS_LAT", "DMS_LONG", "MGRS", "JOG", "FC", "DSG", "PC", "CC1", "ADM1", "POP", "ELEV", "CC2", "NT", "LC", "SHORT_FORM", "GENERIC", "SORT_NAME_RO", "FULL_NAME_RO", "FULL_NAME_ND_RO", "SORT_NAME_RG", "FULL_NAME_RG", "FULL_NAME_ND_RG", "NOTE", "MODIFY_DATE", "DISPLAY", "NAME_RANK", "NAME_LINK", "TRANSL_CD", "NM_MODIFY_DATE", "F_EFCTV_DT", "F_TERM_DT") VALUES ('4', '11276302', '13180565', '42.618893', '76.974295', '42:37:08N', '76:58:27E', '43TFH6191520384', 'NK43-06', 'P', 'PPL', '', 'KG', '07', '', '', '', 'N', 'kir', '', '', 'BAETOVKA', 'Baetovka', 'Baetovka', 'BAETOVKA', 'Baetovka', 'Baetovka', '', '2012-05-09', '1,2,3,4,5,6,7,8,9', '1', '', 'kor_Hang2Latn_ALA_1997', '2011-09-12', '', '');
```

However, it is certainly wrong since the LC (language code) is `kir`, the country code is KG (Kyrgyzstan), there is no transliteration source line and the transliteration of "v" is not supported by the Hang2Latn system.

**Comment by chaaklau** [comment]
> I wonder if "extend" should just be "inherit", or we should separate "extend" and "inherit"...?

I think "extend" can just be "inherit", i.e. if A extends B, then A will inherit character maps, rules and postrules from B. If certain rules are specific to B and should not be inherited by A, then we should create a separate map X which contains only the character map, and then both A and B will extend X.

**Comment by ronaldtse** [comment]
@chaaklau agree. Let's just change "extend" into "inherit". @abunashir could you help us achieve this? Thanks.

**Comment by abunashir** [comment]
Make sense, so let me clarify, we are basically renaming the `extend` to `inherit`, and instead of inheriting only the character mappings, we also want to inherit `rules` and `postrules`, @ronaldtse ?

**Comment by ronaldtse** [comment]
@abunashir correct. I wonder if we should have configuration options to selectively inherit only mappings, rules and postures? Let's just assume we inherit all of those for now.

**Comment by abunashir** [comment]
Yap, I was thinking the same, but I would suggest postponing that configuration option until we actually need it.

**Comment by ronaldtse** [comment]
Agree @abunashir .

**Comment by ronaldtse** [comment]
Ping @chaaklau -- is this now actionable? @abunashir has added the `inherit` feature.
