### ISSUE TITLE
Implement system `kp-kor-hang-latn-2002` (Korean Democratic People's Republic of Korea Korean System (2002)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#121]
This issue is to implement the transliteration system of kp-kor-hang-latn-2002.

This system is referred in the GeoNames database as `kor_Hang2Latn_GKN_2002`, with the system title 'Korean Democratic People's Republic of Korea Korean System (2002)'.

 Tests should rely on the data extracted for the `kor_Hang2Latn_GKN_2002` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by chaaklau** [comment]
I will implement the system outlined in this document:
https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/8th-uncsgn-docs/inf/8th_UNCSGN_econf.94_INF.72.pdf

**Comment by ronaldtse** [comment]
Sounds good, thanks @chaaklau!

**Comment by ronaldtse** [comment]
Done in #206, closing.
