### ISSUE TITLE
Implement system `bgn-kor-hang-latn-1939` (BGN Agreement -- Korean McCune-Reischauer System (1943)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#123]
This issue is to implement the transliteration system of bgn-kor-hang-latn-1939.

This system is referred in the GeoNames database as `kor_Hang2Latn_MR_1939`, with the system title 'BGN Agreement -- Korean McCune-Reischauer System (1943)'.

 Tests should rely on the data extracted for the `kor_Hang2Latn_MR_1939` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by chaaklau** [comment]
A description of the system can also be found here:
http://geonames.nga.mil/gns/html/Romanization/ROMANIZATION%20OF%20KOREAN-%20MR%20for%20DPRK.pdf

**Comment by chaaklau** [comment]
This is the implementation by Unicode chart:
https://github.com/unicode-org/cldr/blob/master/common/transforms/Korean-Latin-BGN.xml

The strategy they use is to convert Hangul into Jamo's, and then replace consonant Jamo sequences one-by-one.

I used another strategy: I create a table that converts Hangul into McCune-Reischauer system, and apply orthographic / phonological transformation rules. This way seems to look neater, but may run into issue if the original text contains non Hangul text.

**Comment by ronaldtse** [comment]
Thanks @chaaklau!

> I used another strategy: I create a table that converts Hangul into McCune-Reischauer system, and apply orthographic / phonological transformation rules. This way seems to look neater, but may run into issue if the original text contains non Hangul text.

I am a little concerned on the maintainability of the long map (basically an exploded map). For example, if I would like to modify the system to use capital "H" for all "ㅎ", I would have to edit the 10,000 entries.

Would the Hangul => Jamo => Latn approach seems a bit easier to maintain?

One thing we should consider in the future is the chaining of the systems. For example, kor/Hang => kor/Latn => kor/Cantonese-Hani. That would be interesting, and adding IPA maps will be good additions.

**Comment by ronaldtse** [comment]
> I am a little concerned on the maintainability of the long map (basically an exploded map). For example, if I would like to modify the system to use capital "H" for all "ㅎ", I would have to edit the 10,000 entries.

In #206 the Jamo map is implemented, I'm wondering if we can rely on the Jamo maps in the 10,000-line Korean maps, or is it not the way to go?

**Comment by ronaldtse** [comment]
Ping @chaaklau anything else needs to be done here?
