### ISSUE TITLE
Implement system `alalc-mal-mlym-latn-1997` (ALA-LC Romanization Table -- Malayalam (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#131]
This issue is to implement the transliteration system of alalc-mal-mlym-latn-1997.

This system is referred in the GeoNames database as `mal_Mlym2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Malayalam (1997)'.

 Tests should rely on the data extracted for the `mal_Mlym2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/521
Test passed and Merged with master.

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
