### ISSUE TITLE
Implement system `bgnpcgn-mkd-cyrl-latn-1981` (BGN/PCGN Romanization Agreement -- Macedonian (1981)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#133]
This issue is to implement the transliteration system of bgnpcgn-mkd-cyrl-latn-1981.

This system is referred in the GeoNames database as `mkd_Cyrl2Latn_BGN_1981`, with the system title 'BGN/PCGN Romanization Agreement -- Macedonian (1981)'.

 Tests should rely on the data extracted for the `mkd_Cyrl2Latn_BGN_1981` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Spec: 
[USBGN_romanization_Macedonian_1981.pdf](https://github.com/riboseinc/interscript/files/4247920/USBGN_romanization_Macedonian_1981.pdf)

Sample implementation: 
https://github.com/unicode-org/cldr/blob/master/common/transforms/Macedonian-Latin-BGN.xml

Data: 
[mkd_Cyrl2Latn_BGN_1981.csv.zip](https://github.com/riboseinc/interscript/files/4247922/mkd_Cyrl2Latn_BGN_1981.csv.zip)

**Comment by andrew2net** [comment]
@ronaldtse in the test data there is "Прлиќ" (line 36) which expected to be converted to "Prliḱ". But in the spec "ќ" -> "ć". Are you sure the test data correct?

**Comment by andrew2net** [comment]
@ronaldtse also in the test data there is "Ѓол" -> "Ðol" (line 100) with `Ð (\u00D0)`. Another line 27 has "Сеѓавечкиот Рид" -> "Seđavečkiot Rid" with `đ (\u0111)`. The problem is `"\u0111".upcase != "\u00D0"`.

**Comment by ronaldtse** [comment]
@andrew2net the source data can contain errors. Can you screen capture those erroneous rows (with the IDs) for further processing? Thanks!
