### ISSUE TITLE
Implement system `bgnpcgn-mkd-cyrl-latn-2013` (BGN/PCGN Romanization Agreement -- Macedonian (2013)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#134]
This issue is to implement the transliteration system of bgnpcgn-mkd-cyrl-latn-2013.

This system is referred in the GeoNames database as `mkd_Cyrl2Latn_BGN_2013`, with the system title 'BGN/PCGN Romanization Agreement -- Macedonian (2013)'.

 Tests should rely on the data extracted for the `mkd_Cyrl2Latn_BGN_2013` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Data: [mkd_Cyrl2Latn_BGN_2013.csv.zip](https://github.com/riboseinc/interscript/files/4247901/mkd_Cyrl2Latn_BGN_2013.csv.zip)

Spec: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/811514/ROMANIZATION_OF_MACEDONIAN.pdf

**Comment by andrew2net** [comment]
@ronaldtse in the spec there is an issue similar to this https://github.com/riboseinc/interscript/issues/158#issuecomment-592475603.
