### ISSUE TITLE
Split rspecs to test each system individually

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#14]
This task is to make rspec generate a spec for every transliteration system so that the results are separate.

https://github.com/riboseinc/interoperable-transliteration/blob/e48db01716f5c2099cf1a0023ab4b8bc35390e93/spec/interscript_spec.rb#L6

**Comment by andrew2net** [comment]
@ronaldtse I haven't found a way to generate specs dynamically for all systems in the maps dir. But I made the test script prints results separately.
I tried to use `expect` for each system in one spec, but in this case, spec stops after a first unexpected result.
So unless we find a way to generate specs dynamically we have 3 option:

- make a new spec for each system by hand
- test all the systems in one spec and stop on first failed expectation
- test all the systems in one spec and print all the results at the end (as is currently done)

Wha do you think?

**Comment by ronaldtse** [comment]
@andrew2net you can look through the file system using Ruby Dir, and metaprogram the specs for each system?

**Comment by andrew2net** [comment]
@ronaldtse RSpec uses metaprogramming itself. If it is possible to metaprogram metaprogramming it should be quite tricky. But I'll try to find how to do it.

**Comment by ronaldtse** [comment]
@andrew2net this is done in 095cb57 now. You can now see each test as a separate RSpec spec, and the results are now accurate. Will post the failures in a new issue.

**Comment by ronaldtse** [comment]
Issue fixed, failed tests in #16 and others.
