### ISSUE TITLE
Implement system `bgnpcgn-nep-deva-latn-1964` (BGN/PCGN Romanization Agreement -- Nepali (1964)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#141]
This issue is to implement the transliteration system of bgnpcgn-nep-deva-latn-1964.

This system is referred in the GeoNames database as `nep_Deva2Latn_BGN_1964`, with the system title 'BGN/PCGN Romanization Agreement -- Nepali (1964)'.

 Tests should rely on the data extracted for the `nep_Deva2Latn_BGN_1964` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
@ronaldtse Here is a [PR](https://github.com/interscript/interscript/pull/370) for this issue

**Comment by ronaldtse** [comment]
@bilashsaha thanks for the PR -- I noticed I forgot to provide the original specification, which is here now:
[BGN_Romanization_Guide_1964_nepali_1964.pdf](https://github.com/interscript/interscript/files/5180758/BGN_Romanization_Guide_1964_nepali_1964.pdf)

<img width="651" alt="Screen Shot 2020-09-07 at 10 21 59 AM" src="https://user-images.githubusercontent.com/11865/92342636-f8cb1780-f0f3-11ea-8890-26a009d20c06.png">
<img width="639" alt="Screen Shot 2020-09-07 at 10 22 15 AM" src="https://user-images.githubusercontent.com/11865/92342648-01235280-f0f4-11ea-850a-2a7eb37d2ff1.png">
<img width="635" alt="Screen Shot 2020-09-07 at 10 22 24 AM" src="https://user-images.githubusercontent.com/11865/92342654-07193380-f0f4-11ea-8fe2-5daede66292e.png">

**Comment by ronaldtse** [comment]
Done in #385
