### ISSUE TITLE
Implement system `alalc-ori-orya-latn-1997` (ALA-LC Romanization Table -- Oriya (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#143]
This issue is to implement the transliteration system of alalc-ori-orya-latn-1997.

This system is referred in the GeoNames database as `ori_Orya2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Oriya (1997)'.

 Tests should rely on the data extracted for the `ori_Orya2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
PR: #599
