### ISSUE TITLE
Implement system `alalc-pan-deva-latn-1997` (ALA-LC Romanization Table -- Panjabi (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#144]
This issue is to implement the transliteration system of alalc-pan-deva-latn-1997.

This system is referred in the GeoNames database as `pan_Deva2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Panjabi (1997)'.

 Tests should rely on the data extracted for the `pan_Deva2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
PR : https://github.com/interscript/interscript/pull/394

**Comment by bilashsaha** [comment]
@ronaldtse this should be done by https://github.com/interscript/interscript/pull/394 . which is merged already

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
