### ISSUE TITLE
Implement system `bgnpcgn-pus-arab-latn-1968` (BGN/PCGN Romanization System -- Pashto (1968)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#147]
This issue is to implement the transliteration system of bgnpcgn-pus-arab-latn-1968.

This system is referred in the GeoNames database as `pus_Arab2Latn_BGN_1968`, with the system title 'BGN/PCGN Romanization System -- Pashto (1968)'.

 Tests should rely on the data extracted for the `pus_Arab2Latn_BGN_1968` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
The spec https://geonames.nga.mil/gns/html/Romanization/Romanization_Pashto.pdf

@ronaldtse I'm not an expert in the family of Arabian languages, it's interesting for me to have a look, but I may spend more time than an experienced person. But if you give me "green light" I will be more then happy)

**Comment by ronaldtse** [comment]
Sorry @CAMOBAP I must have wrongly assigned 😉 

@AhMohsen46 this is for you. Thanks!

**Comment by AhMohsen46** [comment]
issues in https://github.com/interscript/interscript/issues/564
PR https://github.com/interscript/interscript/pull/563

**Comment by ronaldtse** [comment]
Thanks @AhMohsen46 !
