### ISSUE TITLE
Implement system `bgnpcgn-rue-cyrl-latn-2016` (BGN/PCGN Romanization System -- Rusyn (2016)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#148]
This issue is to implement the transliteration system of bgnpcgn-rue-cyrl-latn-2016.

This system is referred in the GeoNames database as `rue_Cyrl2Latn_BGN_2016`, with the system title 'BGN/PCGN Romanization System -- Rusyn (2016)'.

 Tests should rely on the data extracted for the `rue_Cyrl2Latn_BGN_2016` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
Found the spec https://geonames.nga.mil/gns/html/Romanization/ROMANIZATION%20OF%20RUSYN.pdf

**Comment by ronaldtse** [comment]
The spec is correct. Thanks!

**Comment by ronaldtse** [comment]
Done in #557.
