### ISSUE TITLE
Implement system `alalc-rus-cyrl-latn-1997` (ALA-LC Romanization Table -- Russian (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#149]
This issue is to implement the transliteration system of alalc-rus-cyrl-latn-1997.

This system is referred in the GeoNames database as `rus_Cyrl2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Russian (1997)'.

 Tests should rely on the data extracted for the `rus_Cyrl2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
Done
