### ISSUE TITLE
Implement system `bgnpcgn-rus-cyrl-latn-1947` (BGN/PCGN Romanization System -- Russian (1947)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#150]
This issue is to implement the transliteration system of bgnpcgn-rus-cyrl-latn-1947.

This system is referred in the GeoNames database as `rus_Cyrl2Latn_BGN_1947`, with the system title 'BGN/PCGN Romanization System -- Russian (1947)'.

 Tests should rely on the data extracted for the `rus_Cyrl2Latn_BGN_1947` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
Was done a while ago https://github.com/interscript/interscript/blob/master/maps/bgnpcgn-rus-Cyrl-Latn-1947.yaml
