### ISSUE TITLE
Implement system `gost-rus-cyrl-latn-16876-71-1983` (GOST 16876-71: Transliteration of russian words by latin characters

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#151]
This issue is to implement the transliteration system of gost-rus-cyrl-latn-16876-71-1983.

This system is referred in the GeoNames database as `rus_Cyrl2Latn_GOST_1983`, with the system title 'GOST 16876-71: Transliteration of russian words by latin characters'.

 Tests should rely on the data extracted for the `rus_Cyrl2Latn_GOST_1983` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
Duplicate, done in the scope of #294
