### ISSUE TITLE
Implement system `alalc-sin-sinh-latn-1997` (ALA-LC Romanization Table -- Sinhalese (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#153]
This issue is to implement the transliteration system of alalc-sin-sinh-latn-1997.

This system is referred in the GeoNames database as `sin_Sinh2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Sinhalese (1997)'.

 Tests should rely on the data extracted for the `sin_Sinh2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/515

**Comment by ronaldtse** [comment]
#515 merged, thanks @bilashsaha !
