### ISSUE TITLE
Implement system `alalc-mkd-cyrl-latn-1997` (ALA-LC Romanization Table -- Serbian and Macedonian -- Macedonian (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#156]
This issue is to implement the transliteration system of alalc-mkd-cyrl-latn-1997.

This system is referred in the GeoNames database as `srp_Cyrl2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Serbian and Macedonian -- Macedonian (1997)'.

 Tests should rely on the data extracted for the `srp_Cyrl2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Spec: http://catdir.loc.gov/catdir/cpso/romanization/serbian.pdf

Data: [srp_Cyrl2Latn_ALA_1997.csv.zip](https://github.com/riboseinc/interscript/files/4247926/srp_Cyrl2Latn_ALA_1997.csv.zip)

**Comment by andrew2net** [comment]
@ronaldtse isn't this system identical to the #157?

**Comment by ronaldtse** [comment]
@andrew2net yes you are right, but the system should have 2 files instead of 1 (in order to have two system codes for two language codes).

This system can be implemented as an "inherit" system from the other system without any content.
