### ISSUE TITLE
Implement system `bgnpcgn-srp-cyrl-latn-2005` (BGN/PCGN Table of Correspondences -- Serbian (2005)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#158]
This issue is to implement the transliteration system of bgnpcgn-srp-cyrl-latn-2005.

This system is referred in the GeoNames database as `srp_Cyrl2Latn_BGN_2005`, with the system title 'BGN/PCGN Table of Correspondences -- Serbian (2005)'.

 Tests should rely on the data extracted for the `srp_Cyrl2Latn_BGN_2005` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Data: 
[srp_Cyrl2Latn_BGN_2005.csv.zip](https://github.com/riboseinc/interscript/files/4247946/srp_Cyrl2Latn_BGN_2005.csv.zip)

Spec: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/816783/TABLE_OF_CORRESPONDENCES_FOR_SERBIAN.pdf

**Comment by andrew2net** [comment]
@ronaldtse I'm confused by the second row in the [table](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/816783/TABLE_OF_CORRESPONDENCES_FOR_SERBIAN.pdf). The char `Б` is `\u0411` in Unicode but in the table, it is assigned to `\u04D8` which actually is `Ә`.

**Comment by ronaldtse** [comment]
Thanks @andrew2net ! Tracking table error in riboseinc/interscript-references#1 .
