### ISSUE TITLE
Implement system `bgnpcgn-tat-cyrl-latn-2005` (BGN/PCGN Table of Correspondences -- Tatar (2005)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#161]
This issue is to implement the transliteration system of bgnpcgn-tat-cyrl-latn-2005.

This system is referred in the GeoNames database as `tat_Cyrl2Latn_BGN_2005`, with the system title 'BGN/PCGN Table of Correspondences -- Tatar (2005)'.

 Tests should rely on the data extracted for the `tat_Cyrl2Latn_BGN_2005` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
The spec https://geonames.nga.mil/gns/html/Romanization/TABLE%20OF%20CORRESPONDENCES%20FOR%20TATAR.pdf

**Comment by ronaldtse** [comment]
Done in #558, closing.
