### ISSUE TITLE
Implement system `alalc-tel-telu-latn-1997` (ALA-LC Romanization Table -- Telugu (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#162]
This issue is to implement the transliteration system of alalc-tel-telu-latn-1997.

This system is referred in the GeoNames database as `tel_Telu2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Telugu (1997)'.

 Tests should rely on the data extracted for the `tel_Telu2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
Source : http://catdir.loc.gov/catdir/cpso/romanization/telugu.pdf

**Comment by bilashsaha** [comment]
@ronaldtse PR: https://github.com/interscript/interscript/pull/608

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
