### ISSUE TITLE
Implement system `bgnpcgn-tgk-cyrl-latn-1994` (BGN/PCGN Romanization System -- Tajik (1994)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#163]
This issue is to implement the transliteration system of bgnpcgn-tgk-cyrl-latn-1994.

This system is referred in the GeoNames database as `tgk_Cyrl2Latn_BGN_1994`, with the system title 'BGN/PCGN Romanization System -- Tajik (1994)'.

 Tests should rely on the data extracted for the `tgk_Cyrl2Latn_BGN_1994` system in https://github.com/riboseinc/geonames-transliteration-data .

Spec: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/816784/ROMANIZATION_OF_TAJIK.pdf

**Comment by CAMOBAP** [comment]
The spec https://geonames.nga.mil/gns/html/Romanization/ROMANIZATION%20OF%20TAJIK.pdf

**Comment by ronaldtse** [comment]
Done in #561 , closing.
