### ISSUE TITLE
Implement system `bgnpcgn-ukr-cyrl-latn-1965` (BGN/PCGN Romanization System -- Ukrainian (1965)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#184]
This issue is to implement the transliteration system of bgnpcgn-ukr-cyrl-latn-1965.

This system is referred in the GeoNames database as `ukr_Cyrl2Latn_BGN_1965`, with the system title 'BGN/PCGN Romanization System -- Ukrainian (1965)'.

 Tests should rely on the data extracted for the `ukr_Cyrl2Latn_BGN_1965` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Spec: 
[ROMANIZATION OF UKRAINIAN.pdf](https://github.com/riboseinc/interscript/files/4245205/ROMANIZATION.OF.UKRAINIAN.pdf)

The internet location of this system to be encoded is: https://web.archive.org/web/20191023200127/https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/816788/ROMANIZATION_OF_UKRAINIAN.pdf

**Comment by ronaldtse** [comment]
Data: [ukr_Cyrl2Latn_BGN_1965.csv.zip](https://github.com/riboseinc/interscript/files/4245830/ukr_Cyrl2Latn_BGN_1965.csv.zip)

**Comment by andrew2net** [comment]
@ronaldtse we have `maps/bgnpcgn-ukr-Cyrl-Latn-1965.yaml` aready.
