### ISSUE TITLE
Implement system `ua-ukr-cyrl-latn-1996` (Government of Ukraine Ukrainian System (1996)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#185]
This issue is to implement the transliteration system of ua-ukr-cyrl-latn-1996.

This system is referred in the GeoNames database as `ukr_Cyrl2Latn_GUP_1996`, with the system title 'Government of Ukraine Ukrainian System (1996)'.

 Tests should rely on the data extracted for the `ukr_Cyrl2Latn_GUP_1996` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Data: [ukr_Cyrl2Latn_GUP_1996.csv.zip](https://github.com/riboseinc/interscript/files/4245828/ukr_Cyrl2Latn_GUP_1996.csv.zip)

**Comment by andrew2net** [comment]
@ronaldtse are there any mappings and rules for this system?

UPD I found this mapping:
https://en.wikipedia.org/wiki/Wikipedia:Romanization_of_Ukrainian/National_transliteration_table
Is it what we need to implement here?

**Comment by ronaldtse** [comment]
@andrew2net the link refers to http://zakon2.rada.gov.ua/laws/show/55-2010-п which is from 2010. Are we able to find one from 1996?
