### ISSUE TITLE
Implement system `bgnpcgn-urd-arab-latn-2007` (BGN/PCGN Romanization System -- Urdu (2007)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#188]
This issue is to implement the transliteration system of bgnpcgn-urd-arab-latn-2007.

This system is referred in the GeoNames database as `urd_Arab2Latn_BGN_2007`, with the system title 'BGN/PCGN Romanization System -- Urdu (2007)'.

Specification: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/693788/ROMANIZATION_OF_URDU.pdf

Tests should rely on the data extracted for the `urd_Arab2Latn_BGN_2007` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by AhMohsen46** [comment]
@ronaldtse am working on this now, there are two systems in each column, should I implement a map for each?
like in https://github.com/interscript/interscript/pull/441
will kick this off implementing bgnpcgn

**Comment by AhMohsen46** [comment]
Done in PR https://github.com/interscript/interscript/pull/573 
expect for https://github.com/interscript/interscript/issues/572
