### ISSUE TITLE
Implement system `un-urd-arab-latn-1972` (UN Urdu System (1972)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#191]
This issue is to implement the transliteration system of un-urd-arab-latn-1972.

This system is referred in the GeoNames database as `urd_Arab2Latn_UN_1972`, with the system title 'UN Urdu System (1972)'.

 Tests should rely on the data extracted for the `urd_Arab2Latn_UN_1972` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Specification: https://www.eki.ee/wgrs/rom1_ur.htm

Specification: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/pubs/UNGEGN%20tech%20ref%20manual_m87_combined.pdf

<img width="719" alt="Screen Shot 2020-08-06 at 3 09 34 PM" src="https://user-images.githubusercontent.com/11865/89501987-d729f800-d7f6-11ea-8a4e-28dbc20c1632.png">

<img width="729" alt="Screen Shot 2020-08-06 at 3 09 43 PM" src="https://user-images.githubusercontent.com/11865/89502003-dc874280-d7f6-11ea-90e5-3440ea20c3b1.png">

**Comment by AhMohsen46** [comment]
in progress

**Comment by AhMohsen46** [comment]
done/merged in https://github.com/interscript/interscript/pull/583
