### ISSUE TITLE
Implement system `bgnpcgn-uzb-cyrl-latn-1979` (BGN/PCGN Romanization System -- Uzbek Cyrillic (1979)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#192]
This issue is to implement the transliteration system of bgnpcgn-uzb-cyrl-latn-1979.

This system is referred in the GeoNames database as `uzb_Cyrl2Latn_BGN_1979`, with the system title 'BGN/PCGN Romanization System -- Uzbek Cyrillic (1979)'.

 Tests should rely on the data extracted for the `uzb_Cyrl2Latn_BGN_1979` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
I have found only 2000 https://geonames.nga.mil/gns/html/Romanization/TABLE%20OF%20CORRESPONDENCES%20FOR%20UZBEK.pdf

**Comment by ronaldtse** [comment]
The 1979 mapping is found here: http://transliteration.eki.ee/pdf/Uzbek.pdf

**Comment by ronaldtse** [comment]
@CAMOBAP we will have to implement both 1979 and 2000.

**Comment by CAMOBAP** [comment]
Done
