### ISSUE TITLE
Fix test in `un-mon-Mong-Latn-2013`

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#21]
This test comes from http://www.eki.ee/wgrs/rom1_mnc.htm

> Mongolian uses a vertical script. Transcription of Mongolian names is made from their proper pronunciation based on the written form of the Mongolian language and Qahar vernacular, with Zhenglan as its representative pronunciation. Due to the complex nature of the script the romanization scheme is not reversible, e.g. the name of the city Hohhot is written ᠬᠥᠬᠡᠬᠣᠲᠠ but may be transliterated as kökeqota.

```ruby
1) Interscript maps/un-mon-Mong-Latn-2013.yaml system test for {"source"=>"ᠬᠥᠬᠡᠬᠣᠲᠠ", "expected"=>"kökeqota"}

Failure/Error: expect(result).to eq(test["expected"])

  expected: "kökeqota"
       got: "hohehota"

  (compared using ==)
# ./spec/interscript_spec.rb:16:in `block (5 levels) in <top (required)>'
```

However, the expectation is invalid (at least from what I see in the spec), because `kökeqota` cannot be generated -- the grapheme correspondence does not have a mapping target of `ö`...

**Comment by andrew2net** [comment]
@ronaldtse I don't understand how ᠬᠥᠬᠡᠬᠣᠲᠠ can be converted to kökeqota using the existed map. In the map, we have `"ᠬ": "h"` rule only. There aren't other rules with the character.

> Hohhot is written ᠬᠥᠬᠡᠬᠣᠲᠠ but may be transliterated as kökeqota.

Does this mean it may be not transliterated as kökeqota? So if it does, could we translate as hohehota?

**Comment by ronaldtse** [comment]
Clarification from UNGEGN:

> The encoding of Mongolian script is really complex and is based more on phonology rather than the script itself. You might find more information in KNAB's version of the romanization table at http://www.eki.ee/knab/lat/kblcmg2.pdf, particularly in comments to characters 12–13 at the end.

> If you look at the Unicode character names in ᠬᠥᠬᠡᠬᠣᠲᠠ (kökeqota) you'll get Q+OE+Q+E+Q+O+T+A. The name consists of two words, the first of which is köke ('blue'), as the vowels (OE, E) in this word are front vowels and the consonants are usually transliterated k, not q in this case. The second word is qota ('city') and in this case the vowels are back vowels which explains the use of q, not k.

> The bizarre thing [...] is that the Mongolian script itself makes a distinction between k and q but the encoding unites these into one character... [...] the Mongolian script is quite unique in the sense that you cannot read it unless you already know the exact reading of ambiguous characters. And the encoding is based on pronunciation, not the logic of the script itself.

> Just to add that "kökeqota" is based on traditional transliteration of Classical Mongolian, not on the pinyin variant used in Inner Mongolia.
