### ISSUE TITLE
Implement system `elot-ell-grek-latn-743-1982` (ELOT 743:1982)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#221]
This issue is to implement the transliteration system of `elot-ell-grek-latn-743-1982`.

This system is referred in the GeoNames database as `ell_Grek2Latn_ELOT743_1996`, with the system title 'ELOT 743:1982 Information and documentation -- Conversion of Greek characters into Latin characters'.

Tests should rely on the data extracted for the `ell_Grek2Latn_ELOT743_1996` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Test data: 
[ell_Grek2Latn_ELOT743_1996.csv.zip](https://github.com/riboseinc/interoperable-transliteration/files/4168888/ell_Grek2Latn_ELOT743_1996.csv.zip)

**Comment by ronaldtse** [comment]
Spec: https://transliteration.eki.ee/pdf/Greek.pdf

**Comment by ronaldtse** [comment]
We now have the original ELOT 743_1982 document. @opoudjis can you help double-check the system? Thanks!

**Comment by opoudjis** [comment]
Done
