### ISSUE TITLE
Implement system `un-ell-grek-latn-2016` (UN Romanization of Greek 4.0)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#225]
Spec: http://www.eki.ee/wgrs/rom1_el.htm

Comparison of systems: https://transliteration.eki.ee/pdf/Greek.pdf

> The United Nations recommended system was approved in 1987 (resolution V/19), based on the ELOT 743 conversion system of the Greek Standardization Organization. The table was published as an annex to the resolution1.

It can inherit most rules from ELOT 743 but there are minor differences. Those rules can be overridden.

**Comment by opoudjis** [comment]
If you read the fine print, it turns out that ISO 843 1997 TR, UN ELOT 743 1987, and BGN/PCGN 1996 are completely identical. (https://transliteration.eki.ee/pdf/Greek.pdf says that αυ maps to af,av,ay in one and af,av in the other; but the footnote shows that ay is used in the same context in both.)

I think there is a lot of confusion about transliteration schemes, and I am not getting source documents here. 

> It can inherit most rules from ELOT 743 but there are minor differences. Those rules can be overridden.

None of the documentation I have seen demonstrates any such differences.

**Comment by ronaldtse** [comment]
@opoudjis does this help?

[Greek-alphabet-2-english-ELOT-743.pdf](https://github.com/riboseinc/interscript/files/4236542/Greek-alphabet-2-english-ELOT-743.pdf)

**Comment by ronaldtse** [comment]
> If you read the fine print, it turns out that ISO 843 1997 TR, UN ELOT 743 1987, and BGN/PCGN 1996 are completely identical.

This doesn't seem to be accurate. It says on this page: http://www.eki.ee/wgrs/rom1_el.htm
> The transliteration ISO 843:1997 which is also based on ELOT 743 presents the table of type 1 (transliteration of Greek characters into Latin characters) whereby each Greek character has only one Latin equivalent. The following consonants are romanized slightly differently from the UN-approved system

**Comment by ronaldtse** [comment]
"Fifth United Nations Conference on the Standardization of Geographical Names". Writing Systems and Guides to Pronunciation Romanization > Conversion of the Greek alphabet into Latin characters. Paper submitted by Greece and Cyprus.

[e_conf_79_inf38.pdf](https://github.com/riboseinc/interscript/files/4236593/e_conf_79_inf38.pdf)

<img width="715" alt="Screen Shot 2020-02-21 at 10 45 36 PM" src="https://user-images.githubusercontent.com/11865/75044071-fa3c4600-54fb-11ea-86b0-5a047b3d2300.png">
<img width="709" alt="Screen Shot 2020-02-21 at 10 45 46 PM" src="https://user-images.githubusercontent.com/11865/75044083-fe686380-54fb-11ea-9037-82379078fc32.png">
<img width="707" alt="Screen Shot 2020-02-21 at 10 45 51 PM" src="https://user-images.githubusercontent.com/11865/75044087-ff00fa00-54fb-11ea-82a1-1855acdbe2a5.png">
<img width="707" alt="Screen Shot 2020-02-21 at 10 45 57 PM" src="https://user-images.githubusercontent.com/11865/75044088-ff999080-54fb-11ea-8d50-2a40c93b967e.png">
<img width="705" alt="Screen Shot 2020-02-21 at 10 46 02 PM" src="https://user-images.githubusercontent.com/11865/75044091-00322700-54fc-11ea-82ee-fb5963d89541.png">

Resolution 2: Romanization of the Greek alphabet for geographical names.

<img width="709" alt="Screen Shot 2020-02-21 at 11 04 00 PM" src="https://user-images.githubusercontent.com/11865/75045561-73d53380-54fe-11ea-8389-25c8abccd467.png">
<img width="709" alt="Screen Shot 2020-02-21 at 11 04 09 PM" src="https://user-images.githubusercontent.com/11865/75045636-9b2c0080-54fe-11ea-85c1-fe1dcd6592ae.png">

**Comment by ronaldtse** [comment]
@opoudjis please double check source spec. Thanks!

**Comment by opoudjis** [comment]
> > If you read the fine print, it turns out that ISO 843 1997 TR, UN ELOT 743 1987, and BGN/PCGN 1996 are completely identical.
> 
> This doesn't seem to be accurate. It says on this page: http://www.eki.ee/wgrs/rom1_el.htm
> 
> > The transliteration ISO 843:1997 which is also based on ELOT 743 presents the table of type 1 (transliteration of Greek characters into Latin characters) whereby each Greek character has only one Latin equivalent. The following consonants are romanized slightly differently from the UN-approved system

That was only the distinction between macron and sub-macron; that's already been dealt with.

**Comment by opoudjis** [comment]
Confirmed that 1987 and 2016 UN transliterations are identical.

**Comment by ronaldtse** [comment]
Then can we also apply the relationships between the ell systems to indicate they are identical (ie inherit rules)? Thanks.

**Comment by opoudjis** [comment]
Already done. Added phonetic mapping; added `downcase` option to mappings, to allow all-lowercase mappings (which applies to IPA).
