### ISSUE TITLE
Add more tests for `alalc-kat-geor-latn-1997`

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#231]
Originally from #229 

Data from the GNDB using this code does not match the implementation. 

For example, the ALA-LC system uses “x” but other systems use “kh”. In the GNDB data, it is clear that “kh” is oft used and therefore don’t match with this implementation. 

All GNDB entries marked with this system has been added as tests, but only a subset of them work — the rest are commented out. 

We need to have more tests for this system.

**Comment by antonsviridenko** [comment]
@ronaldtse I can rewrite commented out tests according to ALA-LC transliteration rules

**Comment by ronaldtse** [comment]
@antonsviridenko that would be fantastic. Thank you!

**Comment by antonsviridenko** [comment]
ok, some interesting test failures:
`
        expected: "čʻoxuldi"
            got: "čʻoxuldi"
`
visually identical, but one string is Unicode-canonicalized and the second is not
http://unicode.scarfboy.com/?s=c%CC%8C%CA%BBoxuldi
 0063   LATIN SMALL LETTER C
   030C   COMBINING CARON
   02BB   MODIFIER LETTER TURNED COMMA

http://unicode.scarfboy.com/?s=%C4%8D%CA%BBoxuldi
   010D   LATIN SMALL LETTER C WITH CARON
   02BB   MODIFIER LETTER TURNED COMMA

which one must be used in examples and map entries?

**Comment by ronaldtse** [comment]
I think the comparison code should be smart enough to consider them both equal, but right now it might be easiest to do the latter?

The comparison improvement can be filed as a new issue.
