### ISSUE TITLE
Unicode canonicalization in examples and map entries

### ISSUE THREAD

**Issue by antonsviridenko** [interscript/interscript-ruby#238]
Unicode characters can be represented in multiple ways, for example "č" can be 
`010D LATIN SMALL LETTER C WITH CARON`
or
`
0063 LATIN SMALL LETTER C
`
`
030C COMBINING CARON
`
https://github.com/riboseinc/interscript/issues/231#issuecomment-585336635

Therefore it is important to perform Unicode canonicalization on all inputs: character map entries, testing examples and input texts to be converted.

**Comment by ronaldtse** [comment]
I found this article to be a good introduction of using Ruby for Unicode normalization: https://www.honeybadger.io/blog/ruby-unicode-normalization/
