### ISSUE TITLE
Implement system `alalc-ukr-cyrl-latn-2011` (ALA-LC Romanization Table -- Ukrainian (2011)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#246]
This issue is to implement the transliteration system of alalc-ukr-cyrl-latn-2011.

Tests should be added manually.

Spec: https://www.loc.gov/catdir/cpso/romanization/ukrainia.pdf

**Comment by andrew2net** [comment]
@ronaldtse this system looks identical to https://github.com/interscript/interscript/issues/183

**Comment by ronaldtse** [comment]
@andrew2net if it's completely identical, can you make this into an `inherit` entry, e.g. https://github.com/interscript/interscript/blob/af64192e0b3151b76b565c2d9ba7371092a959a8/maps/un-ell-Grek-Latn-1987-ts.yaml

**Comment by andrew2net** [comment]
@ronaldtse sure
