### ISSUE TITLE
Implement system `by-bel-cyrl-latn-2007` (Byelorussian Government of Belarus 2007 System)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#250]
This issue is to implement the transliteration system of by-bel-cyrl-latn-2007.

Tests should rely on the data provided in the spec document.

Spec (original): http://www.pravo.by/pdf/2007-159/2007-159(027-028).pdf
Spec (attached): [2007-159(027-028).pdf](https://github.com/riboseinc/interscript/files/4248107/2007-159.027-028.pdf)

**Comment by CAMOBAP** [comment]
Merged
