### ISSUE TITLE
Implement system `un-bel-cyrl-latn-2007` (National System of Geographic Names Transmission into Roman Alphabet in Belarus)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#251]
This issue is to implement the transliteration system of `un-bel-cyrl-latn-2007`.

Tests should rely on the data provided in the spec document.

Spec: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/9th-uncsgn-docs/crp/9th_UNCSGN_e-conf-98-crp-21.pdf

I believe this system is identical to the one in #250.

**Comment by CAMOBAP** [comment]
@ronaldtse  I have doublechecked and yes it identical, how should I handle this, maybe we should create a soft link?

**Comment by CAMOBAP** [comment]
> I believe this system is identical to the one in #250.

@ronaldtse you are right, should we add some kind of alias here?

**Comment by ronaldtse** [comment]
@CAMOBAP795 we can use the `inherit` option to insert rules and/or maps.

**Comment by CAMOBAP** [comment]
Done
