### ISSUE TITLE
Implement system `gki-bel-cyrl-latn-2000` Byelorussian National Cartographic Authority 2000 system)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#252]
Spec (payment required): https://registr.by/doc/103003

Another link: http://www.pravo.by/document/?guid=3961&p0=W20004488

**Comment by CAMOBAP** [comment]
I have found link to the document in web archive http://web.archive.org/web/20181125224055/http://gki.gov.by/uploads/files/post-GKI-23.10.2000-15.doc

And again it looks like the same as in #250 

@ronaldtse what is expected behavior in this case?


Update: this isn't right document it's included an update from 2006 & 2007 years

Still looking for original doc from 2000

**Comment by ronaldtse** [comment]
Ah -- thanks @CAMOBAP795 for finding something close to the original document... I think there might be minor differences for 2000 vs 2007, so if we can get the original it would be great.

**Comment by CAMOBAP** [comment]
@ronaldtse the 'problem' that 2007 are the same as for #250 and #251

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 for finding the source! Will wait here.

**Comment by CAMOBAP** [comment]
I got docs from  https://registr.by via demo access:
 - [ОБ УТВЕРЖДЕНИИ ИНСТРУКЦИИ ПО ТРАНСЛИТЕРАЦИИ ГЕОГРАФИЧЕСКИХ НАЗВАНИЙ РЕСПУБЛИКИ БЕЛАРУСЬ БУКВАМИ ЛАТИНСКОГО АЛФАВИТА.rev1.txt](https://github.com/riboseinc/interscript/files/4260005/rev1.txt)
 - [ОБ УТВЕРЖДЕНИИ ИНСТРУКЦИИ ПО ТРАНСЛИТЕРАЦИИ ГЕОГРАФИЧЕСКИХ НАЗВАНИЙ РЕСПУБЛИКИ БЕЛАРУСЬ БУКВАМИ ЛАТИНСКОГО АЛФАВИТА.rev2.txt](https://github.com/riboseinc/interscript/files/4260007/rev2.txt)
 - [ОБ УТВЕРЖДЕНИИ ИНСТРУКЦИИ ПО ТРАНСЛИТЕРАЦИИ ГЕОГРАФИЧЕСКИХ НАЗВАНИЙ РЕСПУБЛИКИ БЕЛАРУСЬ БУКВАМИ ЛАТИНСКОГО АЛФАВИТА.rev3.txt](https://github.com/riboseinc/interscript/files/4260008/rev3.txt)

I will analyze it a bit later

**Comment by ronaldtse** [comment]
@CAMOBAP795 fantastic! It seems that the formatting of the tables are strangely arranged, I wonder if a screenshot would work better...

**Comment by CAMOBAP** [comment]
@ronaldtse unfortunately no( because of font indentation is different, In a plain text, I have a chance at least understand what these diacritics belong to

**Comment by ronaldtse** [comment]
@CAMOBAP795 I found this map from UNGEGN that describes the Byelorussian 2000 system! Hope this is useful in reconstructing the original document!

https://unstats.un.org/Unsd/geoinfo/UNGEGN/docs/8th-uncsgn-docs/crp/8th_UNCSGN_econf.94_crp.81.pdf

<img width="762" alt="ECONF 94CRP 81" src="https://user-images.githubusercontent.com/11865/75421800-08fc8000-5976-11ea-981d-8e344ef30e82.png">
￼

**Comment by CAMOBAP** [comment]
Merged
