### ISSUE TITLE
Implement system `apcbg-bul-cyrl-latn-1995` (Toponymic Guidelines for Antarctica)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#256]
This issue is to implement the transliteration system of `bgna-bul-cyrl-latn-2006`.

Spec: http://www.apcbg.org/Toponymic-Guidelines.htm

Toponymic Guidelines for Antarctica, Lyubomir Ivanov. Antarctic Place-names Commission of Bulgaria, Sofia, 1995. 

Examples of this system can be found here:
http://www.apcbg.org/gazet.pdf

**Comment by CAMOBAP** [comment]
Those examples are actually translated (there are no transliterated values)

Researching for transliterated values...

**Comment by CAMOBAP** [comment]
I took random 3 samples for each letter and verified every single one with google, it looks good except a few cases, I left a comments

Generally it's done

**Comment by ronaldtse** [comment]
> I will use names from the map in this research sheet:
https://www.researchgate.net/publication/336103701_Bulgarian_place_names_in_Antarctica

If you used these names, it is perfect -- Lyubomir Ivanov is the person who invented the Bulgarian transliteration systems.

Can we use these names as tests? (There are some entries that may not match because those did not come from transliteration)

**Comment by CAMOBAP** [comment]
> Can we use these names as tests? (There are some entries that may not match because those did not come from transliteration)

@ronaldtse Unfortunately this article contains only Bulgarian names & English names without transliteration

And this is how I add tests:
 1. took original names from http://www.apcbg.org/gazet.pdf
 2. converted them with the `apcbg-bul-cyrl-latn-1995`
 3. after this I have googled every single transliteration and have found relative pages on wiki or Antarctica related publications

Few exceptions:
 - according to rules: `ostrov Kacho` but https://en.wikipedia.org/wiki/Cacho_Island
 - according to rules: `vrah Prinsipe de Asturias` but https://en.wikipedia.org/wiki/Pr%C3%ADncipe_de_Asturias_Peak
 - according to rules: `nunatak Storgoziya` but https://en.wikipedia.org/wiki/Storgozia_Nunatak

I will try to reach Lyubomir Ivanov about those cases

**Comment by ronaldtse** [comment]
> I will try to reach Lyubomir Ivanov about those cases

For all the Bulgarian issues, can you help compile a separate issue so I can contact Lyubomir all at once? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse Totaly make sense, I will report a ticket
