### ISSUE TITLE
Implement system `odni-bel-cyrl-latn-2015` (Office of the Director Of National Intelligence Belarusian 2015 System, ICS-630-01 Annex B)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#263]
This issue is to implement the transliteration system of odni-bel-cyrl-latn-2015.

Name: "Office of the Director Of National Intelligence -- ICS 630-01 -- Belarusian 2015"

Reference: https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20B%20-%20Belarusian_Personal_Names_FLTS%20(U).pdf

**Comment by CAMOBAP** [comment]
Done
