### ISSUE TITLE
Implement system `odni-kat-Geor-Latn-2015` (Office of the Director Of National Intelligence Georgian 2015 System, ICS-630-01 Annex E) 

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#266]
This issue is to implement the transliteration system of odni-kat-cyrl-latn-2015.

Name: "Office of the Director Of National Intelligence -- ICS 630-01 -- Georgian Personal Names 2015"

Reference: https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20E%20-%20Georgian_Personal_Names_FLTS%20(U).pdf

**Comment by ronaldtse** [comment]
@antonsviridenko would you have time for this? Thanks!

**Comment by antonsviridenko** [comment]
@ronaldtse I am unable to download linked pdf, says "404"

**Comment by ronaldtse** [comment]
@antonsviridenko you have access now, thanks.

**Comment by antonsviridenko** [comment]
Looks like this issue has typo in scheme name, should be  `odni-kat-Geor-latn-2015` instead of `odni-kat-cyrl-latn-2015`, Georgian does not normally use Cyrillic script, and the source script in provided document is Georgian

**Comment by antonsviridenko** [comment]
What should I put into the "url" field of the map file? Source to this PDF document inside the private repository?

**Comment by ronaldtse** [comment]
@antonsviridenko I don't think we need the specific URL, maybe we need to have a `source: ICS 630-01, Annex E`. I will add it.

**Comment by ronaldtse** [comment]
> Looks like this issue has typo in scheme name, should be odni-kat-Geor-latn-2015 instead of odni-kat-cyrl-latn-2015, Georgian does not normally use Cyrillic script, and the source script in provided document is Georgian

Yes you're right, sorry about that, fixed now.
