### ISSUE TITLE
Implement system `odni-rus-Cyrl-Latn-2015` (ODNI Russian Personal Names 2015 System, ICS-630-01 Annex K)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#269]
This issue is to implement the transliteration system of `odni-rus-Cyrl-Latn-2015`.

Name: "Office of the Director Of National Intelligence Russian Personal Names 2015 System, ICS-630-01 Annex K"

Reference:
* https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20K%20-%20Russian_Personal_Names_FLTS%20(U).pdf

**Comment by CAMOBAP** [comment]
Done
