### ISSUE TITLE
Need for "transliteration post processing"?

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#27]
I wonder if we need some "post processing" step.

e.g. after transliterating "Sofiya", we can convert it to "Sofia" by matching the closing position.

In #22 we have seen the need that some post processing need for "after transliteration".

In addition, in the Japanese systems, long vowels "oo" are expressed as ô or ō, but we cannot know from simple character replacement (e.g. the doubled "o" is created from single "o"s from different characters).

**Comment by ronaldtse** [comment]
From @andrew2net:
> @ronaldtse we can add postprocessing rules, but this case could be easily solved by the rules we already have.

But we can't currently handle this case:
> long vowels "oo" are expressed as ô or ō, but we cannot know from simple character replacement (e.g. the doubled "o" is created from single "o"s from different characters).

Also, without post-processing we can't select on "already transliterated characters". For example, in Japanese the "っ" character means "repeat the consonant character right after it". In the case of "てっら", it transliterates into "te-っ-ra" which becomes "terra". There is no way to do so without post-processing. The alternative which we do now, is to expand all characters that have "っ" in front, i.e:

```ruby
    "っな": "nna"
    "っに": "nni"
    "っぬ": "nnu"
    "っね": "nne"
    "っの": "nno"
    "っにゃ": "nnya"
    "っにゅ": "nnyu"
    "っにょ": "nnyo"
    "っにゅぅ": "nnyū"
    "っにょぅ": "nnyō"
    "っのぅ": "nnō"
   ...
```

Which is very long-winded and prone to error.

**Comment by andrew2net** [comment]
> For example, in Japanese the "っ" character means "repeat the consonant character right after it". In the case of "てっら", it transliterates into "te-っ-ra" which becomes "terra". There is no way to do so without post-processing.

It can be done using currently implemented rules:
```
map:
  rules:
    - pattern: っ([<list of all consonants>])
      result: "\\1\\1"
```
In this example, a consonant after っ is captured in the pattern and placed at the result twice.

**Comment by ronaldtse** [comment]
It’s a bit different. We are not duplicating the Japanese character, it is the first transliterated character of the Japanese character. You’ll see that in the previously provided example.

**Comment by andrew2net** [comment]
The rules applying followed by the characters applying which replace Japanese characters with Latn.

**Comment by ronaldtse** [comment]
I don’t understand how this could work. Can you demonstrate in the PR?

**Comment by andrew2net** [comment]
You are right, I miss it repeats part of a converted Japanese character (`っra` -> `rra` not `rara`). In this case, we need postprocessing rules.
