### ISSUE TITLE
Implement system `odni-bul-Cyrl-Latn-2015` (ODNI Bulgarian Personal Names 2015 System, ICS-630-01 Annex O)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#272]
This issue is to implement the transliteration system of `odni-bul-Cyrl-Latn-2015`.

Name: "Office of the Director Of National Intelligence Bulgarian Personal Names 2015 System, ICS-630-01 Annex O"

Reference:
* https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20O%20-%20Bulgarian_Person-Name_IC_Standard_FLTS%20(U).pdf

**Comment by CAMOBAP** [comment]
Done
