### ISSUE TITLE
Implement system `odni-uzb-Cyrl-Latn-2015` (ODNI Uzbek Personal Names 2015 System, ICS-630-01 Annex V)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#279]
This issue is to implement the transliteration system of `odni-uzb-Cyrl-Latn-2015`.

Name: "Office of the Director Of National Intelligence Uzbek Personal Names 2015 System, ICS-630-01 Annex V"

Reference:
* https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20V%20-%20Uzbek_Personal_Names_FLTS%20(U).pdf

**Comment by CAMOBAP** [comment]
Done
