### ISSUE TITLE
Implement system `odni-ara-Arab-Latn-2015` (ODNI Arabic Personal Names 2015 System, ICS-630-01 Annex A)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#284]
This issue is to implement the transliteration system of `odni-ara-Arab-Latn-2015`.

Name: "Office of the Director Of National Intelligence Arabic Personal Names 2015 System, ICS-630-01 Annex A"

Reference:
* https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20A%20-%20Arabic_Personal_Names_FLTS%20(U).pdf

**Comment by AhMohsen46** [comment]
done in https://github.com/interscript/interscript/pull/476 except for https://github.com/interscript/interscript/issues/475
