### ISSUE TITLE
Implement system `odni-{hin,urd}-Deva-Latn-2015` (ODNI Hindi Urdu Personal Names 2015 System, ICS-630-01 Annex F)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#286]
This issue is to implement the transliteration system of `odni-{hin,urd}-Deva-Latn-2015`.

Name: "Office of the Director Of National Intelligence Hindi Urdu Personal Names 2015 System, ICS-630-01 Annex F"

Reference:
* https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20F%20-%20Hindi_Urdu_Personal_Names_FLTS%20(U).pdf

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/398

**Comment by ronaldtse** [comment]
Thank you @bilashsaha for the awesome work!

**Comment by ronaldtse** [comment]
Looks like we still have another system for Urdu in Urdu script. Will file new issue.
