### ISSUE TITLE
Implement system `odni-fas-Arab-Latn-2015` (ODNI Persian Farsi Dari Personal Names 2015 System, ICS-630-01 Annex J)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#288]
This issue is to implement the transliteration system of `odni-fas-Arab-Latn-2015`.

Name: "Office of the Director Of National Intelligence Persian Farsi Dari Personal Names 2015 System, ICS-630-01 Annex J"

Reference:
* https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20J%20-%20Persian-Farsi_Dari_Personal_Names_FLTS%20(U).pdf
*  https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20J%20-%20Persian-Farsi_Dari_Personal_Names_FLTS_2018_Revision%20(U).pdf

**Comment by AhMohsen46** [comment]
@ronaldtse the two docs attached, they're like 80% similar
also, each of the docs got two mapping tables, is there a reason we've two docs for this systems?
should I implement a system per doc, or should I compare them and report back while implementing?

**Comment by ronaldtse** [comment]
Clarification sought, let's wait for that. Thanks @AhMohsen46 !

**Comment by ronaldtse** [comment]
The latter is just a revised system. Perhaps only implementing the latter is necessary.

In these documents it describes both Persian and Dari, so they are really two separate systems within each document.

**Comment by AhMohsen46** [comment]
great, Thanks!
will go for the second latter one then; after finishing it will quick-compare it with the first one

**Comment by AhMohsen46** [comment]
implementing latest doc https://github.com/interscript/interscript/pull/510
done except for what's mentioned in #509
