### ISSUE TITLE
Implement system `stategeocadastre-ukr-cyrl-latn-1993` (StateGeoCadastre Ukrainian System (1993))

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#293]
Authority: State Service of Ukraine for Geodesy, Cartography, and Cadastre (Previously "Main Administration of Geodesy Cartography and Cadastre Attached to the Cabinet of Ministers of Ukraine")

Year: 1993

Spec: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/17th-gegn-docs/17th_gegn_WP73.pdf

<img width="543" alt="Screen Shot 2020-05-28 at 2 51 45 AM" src="https://user-images.githubusercontent.com/11865/83060530-2da7e700-a08e-11ea-9edc-6bd06fa6867c.png">
<img width="576" alt="Screen Shot 2020-05-28 at 2 51 56 AM" src="https://user-images.githubusercontent.com/11865/83060543-326c9b00-a08e-11ea-80b8-0cea968d08f2.png">
<img width="556" alt="Screen Shot 2020-05-28 at 2 52 03 AM" src="https://user-images.githubusercontent.com/11865/83060554-36002200-a08e-11ea-85c0-25ce511befdf.png">

**Comment by CAMOBAP** [comment]
<img width="547" alt="Screen Shot 2020-06-01 at 12 14 41 AM" src="https://user-images.githubusercontent.com/2169738/83362845-34d83900-a39d-11ea-88d2-4bdd57601fe5.png">

Trying to understand is this mistype or not looks really strange, trying to find other proofs

**Comment by ronaldtse** [comment]
Looks like a typo indeed! Let’s document that in notes of the system too. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse I wrote letter to land@land.gov.ua let's wait for response

**Comment by CAMOBAP** [comment]
no response from land@land.gov.ua we may fix this on-demand
