### ISSUE TITLE
Add systems from UNGEGN RGMS

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#30]
http://www.eki.ee/wgrs/

**Comment by manuelfuenmayor** [comment]
Added PR for UNGEGN Amharic system in https://github.com/riboseinc/interoperable-transliteration/pull/32

**Comment by manuelfuenmayor** [comment]
Added PR for UNGEGN Arabic System in https://github.com/riboseinc/interoperable-transliteration/pull/33

**Comment by manuelfuenmayor** [comment]
This task was done by other folks.

**Comment by ronaldtse** [comment]
Thanks @manuel489 !
