### ISSUE TITLE
Knowledge gap for the Bulgarian language

### ISSUE THREAD

**Issue by CAMOBAP** [interscript/interscript-ruby#301]
### Problems/Questions

1. `apcbg-bul-cyrl-latn-1995` - https://github.com/interscript/interscript/issues/256#issuecomment-636497935

> - according to rules: ostrov Kacho but https://en.wikipedia.org/wiki/Cacho_Island
> - according to rules: vrah Prinsipe de Asturias but https://en.wikipedia.org/wiki/Pr%C3%ADncipe_de_Asturias_Peak
> - according to rules: nunatak Storgoziya but https://en.wikipedia.org/wiki/Storgozia_Nunatak

2. `alalc-bul-cyrl-latn-1997` - https://github.com/interscript/interscript/issues/80#issuecomment-636487144

> No test data

3. `odni-bul-cyrl-latn-2005` - https://github.com/interscript/interscript/issues/84#issuecomment-636496470

> No test data

### Potential contacts

 - Lybomir Ivanov - http://www.math.bas.bg/logic/ivanovll/Lyubomir-Ivanov.html

**Comment by CAMOBAP** [comment]
Done, waiting for response

**Comment by CAMOBAP** [comment]
According to Lubomir response:

Those names are non-Bulgarian originally and in http://www.apcbg.org/Toponymic-Guidelines.htm there is a note about this

> However, authentic Roman spellings of names of non-Bulgarian origin, and traditional Roman spellings which exist for few Bulgarian names will have priority.

Unfortunately, we cannot automate it except listing every single non-Bulgarian name, which seems impossible

Also, there is no update regarding questions 2 and 3

**Comment by ronaldtse** [comment]
> However, authentic Roman spellings of names of non-Bulgarian origin, and traditional Roman spellings which exist for few Bulgarian names will have priority.

Then we cannot use these names as real tests, for proper transliteration we can only special case them like "Bulgaria".

For 2 and 3, we just have to make up some test data manually.

**Comment by CAMOBAP** [comment]
We can close this task because the only transliteration affected is https://github.com/interscript/interscript/issues/84#issuecomment-636496470 and test data will be generated in the scope of it

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
