### ISSUE TITLE
Implement system `ua-ukr-cyrl-latn-2010` (Government of Ukraine Ukrainian System (2010)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#306]
This issue is to implement the transliteration system of ua-ukr-cyrl-latn-2010.

Authoritative source:  http://zakon2.rada.gov.ua/laws/show/55-2010-п

English spec: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/26th-gegn-docs/WP/WP21_Roma_system_Ukraine%20_engl._.pdf

"The Cabinet of Ministers of Ukraine by its Resolution No 55 of January 27, 2010 "On Normalization of Transliteration of the Ukrainian Alphabet by Means of the Latin Alphabet" approved the “Table of transliteration of the Ukrainian alphabet by means of the Latin alphabet“ and made some changes into Resolution of the Cabinet of Ministers of Ukraine No 231 of 31 March 1995 “On the approval of the rules of registration and issuance of a passport of a Ukrainian citizen for leaving abroad and a travel document of a child, their temporary detention and suppression" and into Resolution No 1873 "On the approval of the rules of registration and issuance, return, custody and extermination of diplomatic and official passports of Ukraine" of November 27, 1998."

Name of system: "Table of Transliteration of the Ukrainian Alphabetby means of the Latin Alphabet"

Approved by: THE CABINET OF MINISTERS OF UKRAINE

Approved source: THE CABINET OF MINISTERS OF UKRAINE RESOLUTION of January 27, 2010 No 55 Kyiv 

Approved on: January 27, 2010

Difference with `ua-ukr-cyrl-latn-1996`:

"The new approved Table is a bit different from the Table of 1996. Taking into consideration the fact that Ukrainian letter "щ" represents two sounds, [ʃ] and [tʃ], from now on the letter "щ" is transliterated as "shch" [ʃtʃ]. The
letter „ь” [j] (soft sign) and the apostrophe (’) are not transliterated according to the Table."

So it can inherit from the 1996 system and override these rules.

**Comment by andrew2net** [comment]
It's implementd in `maps/ua-ukr-Cyrl-Latn-2010.yaml`

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
