### ISSUE TITLE
Implement system mia-bel-Cerl-Latn-2008

### ISSUE THREAD

**Issue by CAMOBAP** [interscript/interscript-ruby#308]
### Intro

During preparing test data for new tests for `icao-bel-Cyrl-Latn-9303` based on real passport's data of my friends (as I  already did in https://github.com/interscript/interscript/commit/68bbc591b51f38ed4103fee78ebe6291479f595c), I have found that some name didn't pass validation, examples:
 - Евгений -> Yauheni
 - Дзмітрый ->Dzmitry

### Investigation

Also, I have found that in Belarus default transliteration a bit different than `icao-bel-Cyrl-Latn-9303` and it regulates by this "internal" doc `8/19678` from "Ministry of Internal Affairs" http://www.pravo.by/document/?guid=2012&oldDoc=2008-261/2008-261(081-092).pdf&oldDocPage=1, its full name is:
"About 8/19678 approval of the Instructions for transliteration of surnames and proper names of citizens of the Republic of Belarus when their personal data is included in the population register"

From other side government docs claims that passport conform "ICAO DOC 9303", prof: http://pravo.by/document/?guid=3871&p0=C21000118

Also, Belorussian citizens may select the transliteration between "Russian" & "Belorussian" styles per request to "Ministry of Internal Affairs" this is why `8/19678` may not always validate this

A nice journalist's research available here https://news.tut.by/society/650761.html

### Action items

 - implement this map too, my proposed name is `mia-bel-Cerl-Latn-2008` (`mia-bel-Cerl-Latn-2010` there is several editions of this doc)

cc @ronaldtse I'm not sure that this is critical/urgent but I think make sense to keep this ticket

**Comment by ronaldtse** [comment]
I found the abbreviation of the Belarussian Ministry of Internal Affairs is MVD (https://www.mvd.gov.by/), so that would be more appropriate?

> Also, Belorussian citizens may select the transliteration between "Russian" & "Belorussian" styles per request to "Ministry of Internal Affairs" this is why 8/19678 may not always validate this

This means that there are 2 systems for `bel` and `rus`.

In this case there are a few systems:
* `mvd-bel-Cyrl-Latn-2008`
* `mvd-rus-Cyrl-Latn-2008`
* `mvd-bel-Cyrl-Latn-2010`
* `mvd-rus-Cyrl-Latn-2010` (only if the 2010 version affect the Russian transliteration)

Can you please help proceed? Thanks!

**Comment by CAMOBAP** [comment]
Got response we are implemented this in the right way
[ответ18.pdf](https://github.com/interscript/interscript/files/4982204/18.pdf)
