### ISSUE TITLE
Create API/website to allow dynamic transliteration 

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#311]
This can be done via an AWS Lambda with this code embedded. Should be straightforward.

Do you have time for this @phuonghuynh?

**Comment by phuonghuynh** [comment]
Yes, @ronaldtse

**Comment by phuonghuynh** [comment]
Could we add LamdbaHandler to this repo?

**Comment by ronaldtse** [comment]
Yup, please create PR. Thanks!
