### ISSUE TITLE
Deploy current version to Gems

### ISSUE THREAD

**Issue by phuonghuynh** [interscript/interscript-ruby#315]
/cc @ronaldtse 

Since lambda-api using quiet old version of the gem

**Comment by phuonghuynh** [comment]
@ronaldtse do you think we should implement GHA for this kind of task?

**Comment by ronaldtse** [comment]
@phuonghuynh do you mean the auto-publish of the gem via GHA to Rubygems?

@CAMOBAP has done that before. @CAMOBAP can you help with this? Thanks!

**Comment by ronaldtse** [comment]
Auto-release at Rubygems works now. Thanks @CAMOBAP !
