### ISSUE TITLE
Document which ISO 639-2 language code is part of SCS identifier (B or T)

### ISSUE THREAD

**Issue by strogonoff** [interscript/interscript-ruby#328]
3-letter codes can be B or T, README doesn’t say which🤔

**Comment by ronaldtse** [comment]
We should define. Interscript can technically be used for both bibliography or terminology, but we should stick to one. 

Let's follow ISO/DIS 24229 (ping @ribose-jeffreylau):
<img width="489" alt="Screen Shot 2020-08-11 at 7 15 23 PM" src="https://user-images.githubusercontent.com/11865/89891068-02518480-dc07-11ea-9b98-710d1b5c7ca9.png">

**Comment by ronaldtse** [comment]
Updated README.
