### ISSUE TITLE
conflict between EKI and UNGEGN

### ISSUE THREAD

**Issue by AhMohsen46** [interscript/interscript-ruby#337]
#336 pull request related for issue #333 

note that some letters are conflicting in transliteration between https://unstats.un.org/unsd/geoinfo/geonames/ and http://www.eki.ee/wgrs/rom1_ar.pdf

example

مِصر "EGYPT" is Mişr in UN
ص is ş

but in http://www.eki.ee/wgrs/rom1_ar.pdf
ص is s̱

also in Qatar
قَطَر
ط is ţ in UN

but in http://www.eki.ee/wgrs/rom1_ar.pdf
ط is ṯ

**Comment by AhMohsen46** [comment]
@ronaldtse issue for UNGEGN

**Comment by ronaldtse** [comment]
Thanks @AhMohsen46 ! I have contacted UNGEGN to see what they think about this discrepancy. Will update!

**Comment by AhMohsen46** [comment]
will be waiting, thanks!

**Comment by ronaldtse** [comment]
@AhMohsen46 from UNGEGN:

> The link you refer to (UN Stats) still contains the previous UN romanization for Arabic and it has not been updated. At the moment the whole database is on the 'waiting list' of things to do [...]

This means that the database uses the previous system and has not been updated to use the new system. Therefore,
1. The Arabic in the UN Stats database data should be extracted and used to test the previous UN Arabic system
2. We need to come up with new examples (or compatible examples) to test the new UN Arabic system.

**Comment by AhMohsen46** [comment]
@ronaldtse so when the UNstats examples conflicts with EKI, I should trust EKI, right?
also, on some -very few cases- conflicts between the two systems are in letters, that they might be blocking testing the specific letters for them both, I either transliterate ص to ş or s̱

**Comment by AhMohsen46** [comment]
I've added a few examples fully covering all the issues open for arabic system and every feature added

**Comment by ronaldtse** [comment]
@AhMohsen46 this means that we should have 2 systems:

1. the 2017 system: https://github.com/interscript/interscript/blob/master/maps/un-ara-Arab-Latn-2017.yaml
2. the 1972 system that is supposed to match with http://www.eki.ee/wgrs/rom1_ar.pdf ("UN 1972 System")

For 2, specifically:
> The previous UN 1972 System had the following differences:
> 1. the character (ظ) was romanized as z̧ instead of 􏰀;
> 2. the cedilla ( ̧) was used instead of sub-macron (_) in all characters with sub-macrons.

Because they should share most rules, you can create an inherited map, you can find examples in the maps directory.

**Comment by ronaldtse** [comment]
@AhMohsen46 once https://github.com/interscript/interscript/issues/347 is done we can close this. Thanks!

**Comment by AhMohsen46** [comment]
from #347 

examples for
kh:
1-خ is kh on UN site
on 2017 it's kẖ
so my assumption it should have been changed from kḩ, but if UN is perfectly fitting 1972, so it's not
Sudan Captial:
الخرطوم
Al Khurţūm
and city in saudi arabia
خــــميس مشــــيط - Khamīs Mushayţ

iy
2- Ar Riyāḑ "الرِياض"
ي with ِ before it is transliterated to ī in 2017
but in UN it's just a normal i, does this mean that in 1972 ي with ِ was just an i

**Comment by AhMohsen46** [comment]
this is good to close, thanks for to great effort @ronaldtse !

**Comment by ronaldtse** [comment]
I've asked UNGEGN about kh vs kh with underbar, let's see what the response will be. Thanks!

**Comment by ronaldtse** [comment]
kh is explained here: https://github.com/interscript/interscript/issues/347#issuecomment-684777658
