### ISSUE TITLE
kp-kor-Hang-Latn-2002: some un-transliterated characters

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#341]
Perhaps we should make this a spec.

Some characters are not covered by existing Jamo => Latn rules:
* Kuhyŏᆫ (trailing ᆫ)
* Paeyŏᆯ (trailing ᆯ)
* Khŏmphyuthiᆼ (trailing ᆼ)

Original:
> 세계를 향한 대화, 유니코드로 하십시오. 제10회 유니코드 국제 회의가 1997년 3월 10일부터 12일까지 독일의 마인즈에서 열립니다. 지금 등록하십시오. 이 회의에서는 업계 전반의 전문가들이 함께 모여 다음과 같은 분야를 다룹니다. - 인터넷과 유니코드, 국제화와 지역화, 운영 체제와 응용 프로그램에서 유니코드의 구현, 글꼴, 문자 배열, 다국어 컴퓨팅.

``` sh
$ bundle exec bin/interscript samples/hangul.txt --system kp-kor-Hang-Latn-2002
Segyerül Hyanghan Taehwa, Yunikhodüro Hasipsio. Je10hoe Yunikhodü Kukje Hoeüiga 
1997nyŏn 3wol 10ilbuthŏ 12ilkkaji Togirüi Mainjüesŏ Yŏllimnida. Jigüm Tüngnokhasipsio. 
I Hoeüiesŏnün Ŏpkye Jŏnbanüi Jŏnmun-gadüri Hamkke Moyŏ Taümgwa Katthün 
Punyarül Tarumnida. - Inthŏnetkwa Yunikhodü, Kukjehwawa Jiyŏkhwa, Unyŏng Chejewa
Üngyong Phürogüraemesŏ Yunikhodüüi Kuhyŏᆫ, Külkkoᆯ, Munja Paeyŏᆯ, Tagugŏ
Khŏmphyuthiᆼ.
```

**Comment by webdev778** [comment]
I fixed it
`bundle exec bin/interscript samples/hangul.txt --system kp-kor-Hang-Latn-2002
Segyerül Hyanghan Taehwa, Yunikhodüro Hasipsio. Je10hoe Yunikhodü Kukje Hoeüiga 1997nyŏn 3wol 10ilbuthŏ 12ilkkaji Togirüi Mainjüesŏ Yŏllimnida. Jigüm Tüngnokhasipsio. I Hoeüiesŏnün Ŏpkye Jŏnbanüi Jŏnmun-gadüri Hamkke Moyŏ Taümgwa Katthün Punyarül Tarumnida. - Inthŏnetkwa Yunikhodü, Kukjehwawa Jiyŏkhwa, Unyŏng Chejewa Üngyong Phürogüraemesŏ Yunikhodüüi Kuhyŏn, Külkkol, Munja Paeyŏl, Tagugŏ Khŏmphyuthing.`

**Comment by ronaldtse** [comment]
Closed in #430 . Thanks @webdev778 !
