### ISSUE TITLE
Automatically push interscript js to interscript-js repo

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#358]
On release tag, automatically generate interscript.js and maps.json to interscript-js repo.

https://github.com/interscript/interscript-js/

**Comment by CAMOBAP** [comment]
@ronaldtse let me know if we have some existing TOKEN variable anme already for this

**Comment by ronaldtse** [comment]
I've added the INTERSCRIPT_CI_PAT for the interscript-ci user.

**Comment by CAMOBAP** [comment]
Done
