### ISSUE TITLE
(The Survey of Egypt System) ses-ara-arab-latn-1930 inquiry

### ISSUE THREAD

**Issue by AhMohsen46** [interscript/interscript-ruby#362]
1-do we have a dataset for The Survey of Egypt System?
2-also, in [doc](http://www.eki.ee/wgrs/rom1_ar.pdf)  Not all the variations have been given above., is there is a better resource?, or is this all what we need to transliterate based on Survey of Egypt System?
3-just to assure ḏ = ḍ this is a dot under d instead of sub-macron (_); it's not a the cedilla (¸), right?

**Comment by AhMohsen46** [comment]
point 3 can be disregarded based on examples [here](https://www.loc.gov/maps/?fa=subject%3Amaps%7Ccontributor%3Aegypt.+maslahat+al-misahah&dates=1930-1939&st=list&c=50&all=true)

**Comment by ronaldtse** [comment]
We don't have a specific database for the SES system, but maybe their maps as you have found will contain those names?

**Comment by AhMohsen46** [comment]
@ronaldtse as for point 2, I've implemented all available variations from 2017, I guess this is okay to be closed unless proven otherwise by any examples
