### ISSUE TITLE
Differentiate un-ara-Arab-Latn-{1971,1972} systems

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#364]
From UNGEGN:

> kh with underline(s) was only in the initial draft (1971), probably in order to show that two Latin letters jointly refer to one Arabic character, and most likely it should be represented by a double underline in a digital format.

> The source is referred to in Resolution II/8 (http://www.eki.ee/wgrs/res/res_2_8.htm). kh was there given without any diacritics.

> The table itself is also reproduced in a WGRS document on Arabic, earlier versions than 2017 (e.g. http://www.eki.ee/wgrs/obs_rom_vers/rom1_ar_v4_0.pdf).

> [The authoritative source ] it is on page 170 (175 in a digital copy) in https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/2nd-uncsgn-docs/E_Conf61_4_Add1_e.pdf.

The full page attached below:
<img width="932" alt="Screen Shot 2020-09-01 at 10 08 30 PM" src="https://user-images.githubusercontent.com/11865/91861668-acb94680-ec9f-11ea-8b8a-a5323f5813da.png">
<img width="895" alt="Screen Shot 2020-09-01 at 10 08 37 PM" src="https://user-images.githubusercontent.com/11865/91861686-b04ccd80-ec9f-11ea-8e87-bc920656beee.png">

There are actually 2 systems:
* 1971 "Beirut system"
* 1972 "Modified Beirut system"

The 1972 system is the one finally approved by UN.

We need to differentiate these two and label them as "Beirut system" vs "Modified Beirut system".

_Originally posted by @ronaldtse in https://github.com/interscript/interscript/issues/347#issuecomment-684882413_

**Comment by AhMohsen46** [comment]
as per my understanding now, 1971 is in the table in the screenshot attached page 175 in the document

here in this link http://www.eki.ee/wgrs/res/res_2_8.htm
it states the following to reference: 1 – Second United Nations Conference on the Standardization of Geographical Names: Vol. II. Technical papers, 1972, p. 31.

page 31(38 digital copy), page 31 got line under kh

the only match I see for the description is page 175 "recommended amendment " column

**Comment by AhMohsen46** [comment]
@ronaldtse 
in examples page 170, all the articles are having `-` between the definition and the word, not sure if that's a rule that they forgot mentioning, as there is a similar one in Egypt 1930; where all the articles are defined with - separating instead of a normal space

**Comment by AhMohsen46** [comment]
PR https://github.com/interscript/interscript/pull/365 fixes this

**Comment by ronaldtse** [comment]
Thanks @AhMohsen46 !
