### ISSUE TITLE
Implement system `bgnpcgn-srp-cyrl-latn-1962` (BGN/PCGN Serbian (1964, 1962))

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#381]
[BGN_Romanization_Guide_1964_serbian_1962.pdf](https://github.com/interscript/interscript/files/5180818/BGN_Romanization_Guide_1964_serbian_1962.pdf)

**Comment by ronaldtse** [comment]
@andrew2net could you help handle this?

**Comment by andrew2net** [comment]
@ronaldtse shouldn't it be named "bgnpcgn-**srp**-cyrl-latn-1962"? We have "bgnpcgn-srp-Cyrl-Latn-2005.yaml" so I think it should be similar.

**Comment by ronaldtse** [comment]
@andrew2net yes you're right, please help fix it, thanks!
