### ISSUE TITLE
Implement system `dos-nep-deva-latn-1997` (Nepal Survey Department Nepali (1997))

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#383]
Survey Department, Ministry of Land Management, Cooperatives and Poverty Alleviation, Government of Nepal.
<img width="531" alt="Screen Shot 2020-09-07 at 10 47 36 AM" src="https://user-images.githubusercontent.com/11865/92343885-8bb98100-f0f7-11ea-8cb2-c7d4a66bd0ff.png">
[translation2.pdf](https://github.com/interscript/interscript/files/5180860/translation2.pdf)
<img width="615" alt="Screen Shot 2020-09-07 at 10 51 52 AM" src="https://user-images.githubusercontent.com/11865/92344118-24e89780-f0f8-11ea-992f-4f335e8a4e05.png">

The original link was http://nationalgeoportal.gov.np/old/pdf/translation2.pdf but it's now gone. At least we have it here.

**Comment by ronaldtse** [comment]
For @bilashsaha

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/392
