### ISSUE TITLE
Issues in BGN/PCGN Romanization for Arabic (1956) specification

### ISSUE THREAD

**Issue by AhMohsen46** [interscript/interscript-ruby#386]
In this [original specification](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/858000/ROMANIZATION_OF_ARABIC.pdf)

1-  `الثُّلَيثُوَات` is transliterated to `ath thulaythuwāt`

I assume there is a missing sokoon that had to be on `ya'` so it had to be like this `الثُّلَيْثُوَات`
otherwise it'd have been transliterated to `ath thulaīthuwāt` given this example from the same doc

![image](https://user-images.githubusercontent.com/34799755/92395805-3b0c4d00-f124-11ea-8355-855b35916b61.png)

2-  `مَزََّة ڤِيلَّات غَرْبِيَّة` is transliterated to `Mazzah Vīllāt Gharbīyah`
I assume this is because that's a Non-Standard Arabic, so the rule of differentiating between `ة` being `ah` or `at` doesn't apply here, not sure if there's a specific rule for that

**Comment by ronaldtse** [comment]
@AhMohsen46 for 2, what will that be transliterated according to the system if strictly enforced?

**Comment by AhMohsen46** [comment]
expected: "Mazzah Vīllāt Gharbīyah"
got: "mazzat vīllāt gharbīyah"

the `ة` is tranlisterated to `at` instead if `ah`, based on the fact that the system may consider `مَزََّة` as "modaf"
same as in `جُمهوريَّة مِصر العَرَبية` being transliterated to `jumhūrīyat mis̱r al ‘arabīyah`

**Comment by ronaldtse** [comment]
![image](https://user-images.githubusercontent.com/11865/92438879-4ae76800-f1dc-11ea-9953-f6ca9e535191.png)
![image](https://user-images.githubusercontent.com/11865/92438884-4e7aef00-f1dc-11ea-865c-a532bfa4a105.png)

Sorry I'm a bit lost... These rules say that if the "ة" is in an "idafah" noun phase, it should become "t" instead of "h".

The question is, is مَزََّة ڤِيلَّات غَرْبِيَّة an "idafah" construction?

Just trying to clarify before sending the report. Thanks.

**Comment by AhMohsen46** [comment]
@ronaldtse sorry for not explaining further in the issue description
so, yes for the system, it seems like an"idafah", exactly the same as "محافظة بغداد"

our system is currently detecting `ah`

we're detecting definite articles so the `ة` is transliterated to `ah`
we're detecting ة at the end of the sentence like in حماة to transliterate it to `ah`
otherwise it's `at`

the point with `مَزََّة ڤِيلَّات غَرْبِيَّة` I assume is it's originally a city called [المرة](https://en.wikipedia.org/wiki/Mezzeh)
فيلات is "villas", غربية is "western"
so I guess the main issue is it's a composite name from non standard arabic, that's why it might be more complicated for the 3 rules above to detect it

**Comment by ronaldtse** [comment]
Got it. @AhMohsen46 then is the following explanation accurate?

1. Our system can't recognize all "idafah" yet (because it's complex, obviously).
2. We have some way of recognizing some "idafah" but because this name is a composite name from non-standard Arabic, the "idafah" is more difficult to detect.

**Comment by AhMohsen46** [comment]
@ronaldtse yes, this briefs it perfectly

**Comment by ronaldtse** [comment]
@AhMohsen46 does this mean this issue is something we should improve on, or is this a bug of the system?

**Comment by AhMohsen46** [comment]
@ronaldtse I would say the system is doing great detecting how to transliterate almost 100% of `ة` across different positions of the sentence, but this was a corner case, that I assume won't frequently occur -maybe it'll in persian and urdu, can't say am 100% certain about these-
as the word origin is مزة as in this [like](https://en.wikipedia.org/wiki/Mezzeh)
and فيلات غربية is "western villas"
I guess it might be like `avenue` for example in New York avenue, it's not a part of the name, it's something describing properties of the place
and it's a composite word, I mean even me myself as a native speaker, if I've never heard of it
I'd definitely pronounce it as `mazzat vīllāt gharbīyah`

**Comment by ronaldtse** [comment]
> I'd definitely pronounce it as `mazzat vīllāt gharbīyah`

Or do you mean `mazzah vīllāt gharbīyah`?

**Comment by AhMohsen46** [comment]
@ronaldtse no, I'd say it mazzat -if I've never heard before-, weird I know, I've done more research
apparently, the word مزَّة origin is Roman
I guess the source of this conflict is that the `western villas` area name is attached to the city name which is `mazzah`
we're using it for different purposes in arabic nowadays, we call some kind of food مزَّة for example
it's definitely an outlier

**Comment by ronaldtse** [comment]
Clarification received!

Original questions:

> 1. Table 1 row 5 transliterates الثُّلَيثُوَات to "ath thulaythuwāt”. 
> According to my colleague, the BGN/PCGN system will lead to "ath thulaīthuwāt”, not "ath thulaythuwāt”. (thulaī instead of thulay)
>
> The usage of “ay” in the above example may have come from the rule in Table 2 row 9.
> 
> If that’s the case, there is a “missing sokoon on ya’ “ in the Arabic sample in Table 1 row 5.

Response 1: “The sokoon here is implied by the diacritic on the previous letter (fat.ha = ‘a’). The letter combination of ل followed by ي can only result in two possible transliterations: “lay” or “lī”. “Laī” does not comply with Arabic orthography.”
 
Response 2: “The Arabic diacritic known as the sukūn​ is not always written and is therefore not incorrect as written in the example. The character ي in this instance is followed by the fatha on the previous consonant ل, which in turn makes this letter act as a consonant in this word. This works basically the same way as the 'y' in English - it can sometimes be used as a vowel as in 'baby' and sometimes a consonant as in 'stay'.
 
This is the same for the Arabic letter و - when followed by a consonant with a short vowel diacritic or another long vowel, or if the word begins with و, it is treated as a 'w' in transliteration. (Ex: وادي = Wādī; خور = Khawr)”

> 2. Table 3 row 3 transliterates مَزََّة ڤِيلَّات غَرْبِيَّة  to “mazzah vīllāt gharbīyah”.
> 
> We wonder if there is some additional rule that applies here because this term is non-standard Arabic.
> 
> In our interpretation of the BGN/PCGN system, this may have been "mazzat vīllāt gharbīyah” instead of “mazzah vīllāt gharbīyah”. (mazzat instead of mazzah). This place name means “western villa [district] of mazzah”.
>
> The reason for “mazzat instead of mazzah” is due to Table 1 rule 30, together with Note 4 (and Note 4’s footnote 7). Table 1 rule 30 states that the ة is transliterated as “ah" or “at”. The third example demonstrates the transliteration to “at”.
>  
> In Note 4 footnote 7, it describes if a word uses the “idafah” grammatical construction, it should be transliterated as “at” not “ah”.
>
> Here, the example "mazzah vīllāt gharbīyah” seems to use an “idafah” construction, and therefore might have been "mazzat vīllāt gharbīyah”.
> 
> However, according to my colleague, this phrase is non-standard Arabic and this example may be an outlier.
 
Response: “This rule does not apply when the first word ending with ة is a proper noun”

----

@AhMohsen46 are we all good here? Thanks!

**Comment by ronaldtse** [comment]
Also, we are also meant to add these examples to the Arabic (1956) system:

سیٌد Seyyed
میدان Meydān
فردوسی Ferdowsī (if this was romanized "Ferdosī", we would reverse render it as فردسی) The "o" would suggest a short vowel, not represented in written script.

(originally from https://github.com/interscript/interscript/issues/509#issuecomment-728710139)

**Comment by AhMohsen46** [comment]
from what he said for the first question 

> The Arabic diacritic known as the sukūn​ is not always written and is therefore not incorrect as written in the example

this means either with sokoon or without, will be done the same way?
https://github.com/interscript/interscript/pull/647

@ronaldtse sorry to bother you if that's gonna take too long
as for the 3 examples below am not sure they are for this system, since damma is u and kasra is i
فردوسی is Firdwsī  for example

I can see kasra is being transliterated to e, and damma to o

I can see this case only here https://github.com/interscript/interscript/blob/ce97173d83000f335aafae284bae41996da9178f/maps%2Fbgnpcgn-per-Arab-Latn-1958.yaml#L218-L219
but here و is w

and و is o here 
https://github.com/interscript/interscript/blob/f3beb7c0968965eeff674d74a840e22cb976f7b5/maps%2Fbgnpcgn-bal-Arab-Latn-2008.yaml#L259

https://github.com/interscript/interscript/blob/187080885f2e53b9e75f6172a0ab9cc10ebca000/maps%2Fbgnpcgn-urd-Arab-Latn-2007.yaml#L320

however, in both of them, ُ  is w

**Comment by ronaldtse** [comment]
>> Response 1: “The sokoon here is implied by the diacritic on the previous letter (fat.ha = ‘a’). The letter combination of ل followed by ي can only result in two possible transliterations: “lay” or “lī”. “Laī” does not comply with Arabic orthography.”

> this means either with sokoon or without, will be done the same way?

I think "Response 1" means that the "sokoon" can be inferred from the "itic on the previous letter (fat.ha = ‘a’)" so we should add the sokoon that way?

> as for the 3 examples below am not sure they are for this system, since damma is u and kasra is i

I think you are right -- I Googled these places and they are all Persian. They probably belong to the BGN/PCGN Persian system.

**Comment by AhMohsen46** [comment]
as for response one, I think yes, this might be what he meant, am going to add a pre-processing rule to add sokoon over ي in case it's preceded by fatha and ل

adding to PR: https://github.com/interscript/interscript/pull/647/files
as for second reply, sounds great, Thanks!
