### ISSUE TITLE
Test against GeoNames data (Hong Kong)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#39]
The data is available here:
[hk.zip](https://github.com/riboseinc/interoperable-transliteration/files/4022801/hk.zip)

### Example 1

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/11865/71773766-a787e880-2fa6-11ea-9e2d-beb5d04dde6f.png">

(As with #38 , FULL_NAME_{RO/RG} are the source data)

In the first entry, the source rows are:
* "NS | zho" "永寧里"
* "N | zho" "Wing Ning Lei"

They are generated into:
* "VS | zho" "永宁里"
* "V | zho" "Yongningli"

### Example 2

<img width="1163" alt="Screen Shot 2020-01-05 at 10 32 55 AM" src="https://user-images.githubusercontent.com/11865/71773779-c71f1100-2fa6-11ea-8e36-4bd3e0771164.png">

TRANSL_CD:

<img width="93" alt="Screen Shot 2020-01-05 at 10 33 01 AM" src="https://user-images.githubusercontent.com/11865/71773778-c6867a80-2fa6-11ea-9220-1b6362387f6b.png">

Source rows:
* "C" (convention, indicating this name is an official source) "Hong Kong"
* "NS | zho" "香港"

Is generated into:
* "N | zho" "Heung Kong"
* "V | zho" "Xianggang" (this entry has a transliteration system code entered as "zho_Hani2Latn_GCH_1979")

### Summary

We need to generate the transliteration entries from the source data for both examples.

**Comment by ronaldtse** [comment]
Ping @chaaklau

**Comment by chaaklau** [comment]
## Extracting transliterations form source file

For Hong Kong, there should be at least four Chinese *LC=='zho'* names for each entry.  **NS**: Traditional Chinese, **N**: Cantonese Romanisation, **VS**: Simplified Chinese Characters, **V**: Hanyu Pinyin. The attempt is to extract all good pairs of (NS, N) for Cantonese, and (VS, V) for Mandarin from the source data.

Note that:
* The error rate in the data is a bit high (about 20% of the entries are not useable), e.g. incorrect LC or NT tags, gaps, typos, etc.
* **MGRS is not unique for place names!**, e.g. for MGRS == '50QKK3603795975', there are six NS (Traditional Chinese) names, and six names that are marked as N (Cantonese transliteration), with the LC column labelled as "zho", we need to guess which is which.

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>MGRS</th>
      <th>NT</th>
      <th>LC</th>
      <th>FULL_NAME_RO</th>
      <th>TRANSL_CD</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>41</td>
      <td>50QKK3603795975</td>
      <td>N</td>
      <td>zho</td>
      <td>Pak Lap Wan</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>42</td>
      <td>50QKK3603795975</td>
      <td>NS</td>
      <td>zho</td>
      <td>白腊灣</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>94</td>
      <td>50QKK3603795975</td>
      <td>N</td>
      <td>zho</td>
      <td>Chau Pui</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>95</td>
      <td>50QKK3603795975</td>
      <td>NS</td>
      <td>zho</td>
      <td>洲背</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>144</td>
      <td>50QKK3603795975</td>
      <td>NS</td>
      <td>zho</td>
      <td>洲尾角</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>146</td>
      <td>50QKK3603795975</td>
      <td>N</td>
      <td>zho</td>
      <td>Chau Mei Kok</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>232</td>
      <td>50QKK3603795975</td>
      <td>N</td>
      <td>zho</td>
      <td>Ping Chau</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>233</td>
      <td>50QKK3603795975</td>
      <td>NS</td>
      <td>zho</td>
      <td>平洲</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>447</td>
      <td>50QKK3603795975</td>
      <td>NS</td>
      <td>zho</td>
      <td>亞媽灣</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>450</td>
      <td>50QKK3603795975</td>
      <td>N</td>
      <td>zho</td>
      <td>A Ma Wan</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>4357</td>
      <td>50QKK3603795975</td>
      <td>NS</td>
      <td>zho</td>
      <td>更樓石</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>4360</td>
      <td>50QKK3603795975</td>
      <td>N</td>
      <td>zho</td>
      <td>Kang Lau Shek</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

## Processing

1. First I have grouped all 'zho' entries using **MGRS**, this dataframe will then be used to generate the (NS, N) pair (i.e. Traditional Chinese to Cantonese romanisation). 
1. The order of the list is unreliable, but it is assumed here that Traditional Chinese and its romanised form should be adjacent to each other.
1. A separate character-syllable list will also be generated.

(For brevity I will skip the code, please refer to the attached Jupyter Notebook for details)

## Cantonese

Here are the stats.

    Good pairs 1341, (Both Traditional Chinese names and transliteration are provided)
    Syll mismatch 26, (Number of syllables do not look right, hence excluded)
    Missing N 176, (No romanisation provided, probably there is a non-transliteration conventional name)
    Missing NS 79, (No TC names provided)
    Mismatch 28 (Names and romanisations do not match, e.g. two TC names but only one Cantonese transliteration)

(Sample data removed for brevity)

Good pairs for Cantonese are then exported to csv. 
The first column is TC, and the second column is Transliteration


## Mandarin

Stats:

    Good pairs 723, 
    Missing N 7, 
    Missing NS 621, 
    Mismatch 201

**Jupyter Notebook**
[HK GeoNames.ipynb.zip](https://github.com/riboseinc/interoperable-transliteration/files/4026445/HK.GeoNames.ipynb.zip)
**Extracted transliteration pairs**
[cantonese_pairs.txt](https://github.com/riboseinc/interoperable-transliteration/files/4026448/cantonese_pairs.txt)
[mandarin_pairs.txt](https://github.com/riboseinc/interoperable-transliteration/files/4026449/mandarin_pairs.txt)

## Summary

Extracted Cantonese and Mandarin data from hk.txt, retrieved 1341 (Cantonese) and 723 (Mandarin) pairs respectively. These entries can be used for testing, but are not good enough in terms of size and quality for the generation of mapping file.

`P.S. I am aware that the Mandarin names need to follow word-spacing rules, and these rules can be hard to implement. Will come back to this later. Cantonese transliterations have a space between syllables, so should be more straightforward.`

**Comment by chaaklau** [comment]
Since we cannot generate map using GeoNames data, I am going to use the [OGCIO list] to generate a syllable list for Cantonese transliteration. 

The list is originally available [here](
https://www.ogcio.gov.hk/tc/our_work/business/tech_promotion/ccli/cliac/canton_pronun_list.html), and has recently been re-uploaded to [GitHub](https://github.com/lshk-org/jyutping-table) with a CC-4.0 license. 

This is also related to #13 
I will create two .yaml maps, one for Jyutping, one for Loose Governmental Transliteration used in the GeoNames dataset.

**Comment by ronaldtse** [comment]
Thanks @chaaklau . Just to clarify, that we need to add the maps for Jyutping + Loose Governmental Transliteration, in order to calculate the names in the GeoNames dataset.

> NS: Traditional Chinese, N: Cantonese Romanisation, VS: Simplified Chinese Characters, V: Hanyu Pinyin. 

This is not accurate -- the GeoNames NT column only means: (see #38):
![image](https://user-images.githubusercontent.com/11865/71825778-88d53f00-30d7-11ea-81d7-278b66bfc3e5.png)

The point is to use the GeoNames data set to discover transliteration pairs and use them as test data for the maps for transliteration. Notice that in the GeoNames data set, the "C", "N", "NS" names cannot be changed even if they are transliterated (perhaps using a prior transliteration system). There are many of these examples in Hong Kong (e.g. Rambler Channel).

**Comment by ronaldtse** [comment]
For GeoNames, one goal that is possible is to reduce the transliterated forms from words. For example, many of the V, VA, VS names are actual transliterations of the NS. If so, those can be re-generated using NS and can be actually marked as "derived". 

This is one goal we want to achieve moving down the road. But all this depends on us having a good/proper transliteration map.

**Comment by chaaklau** [comment]
Thanks for the clarification. I have created a map for Jyutping, and will generate one for Gov from Jyutping.

For Loose Governmental Transliteration, there could be multiple valid transliterations for the same name, e.g. 灣仔 can be **Wan Chai** (Hong Kong Island) or **Wan Tsai** (Sai Kung). How should this be handled?

**Comment by ronaldtse** [comment]
> For Loose Governmental Transliteration, there could be multiple valid transliterations for the same name, e.g. 灣仔 can be Wan Chai (Hong Kong Island) or Wan Tsai (Sai Kung). How should this be handled?

We can have a map that leads 仔 to "Ch" and "Ts":

```yaml
仔:
  - Ch
  - Ts
```

But we won't be able to differentiate them during generation. It's either the first or the second. If we use the first, then "Tsai" will be the anomaly (i.e. we consider it not created from transliteration).

**Comment by chaaklau** [comment]
## Mandarin transliteration in HK data

Extracted a list of Mandarin transliteration from the Hong Kong dataset, and created a toneless pinyin map for testing.

1. Spacing
Hanyu Pinyin (zho_Hani2Latn_GCH_1979) has detailed rules on word segmentation. These rules have not yet been implemented. Whether a space is needed depends on a number of factors, and cannot be handled by mapping rules alone. For example, these place names below all contain the character "灣", but only the first and third rows below are transliterated as one word. 

![image](https://user-images.githubusercontent.com/5143421/71959430-b3391080-322d-11ea-9b15-fef35dfac38b.png)

A separate parsing layer may be needed in order to handle the insertion of space (related to #44 ).

2. Syllable separator for zero-onset syllables
Syllables begin with **a**, **o**, and **e** should be preceded by a syllable separator `’` unless it is the first syllable of a word, e.g. 西安 Xi’an.

3. Hong Kong specific reading
涌: *Chong*
仔: *Zai*
咀: *Zui*  (<嘴)

**Toneless Pinyin Map with HK place names**
[cn-chn-Hans-Latn-pinyin_toneless.yaml.zip](https://github.com/riboseinc/interoperable-transliteration/files/4034086/cn-chn-Hans-Latn-pinyin_toneless.yaml.zip)

**Comment by ronaldtse** [comment]
@chaaklau the rules on word segmentation can somewhat be mitigated by a shortcut -- 
<img width="565" alt="Screen Shot 2020-01-08 at 5 52 23 PM" src="https://user-images.githubusercontent.com/11865/71968320-a0c7d280-323f-11ea-89ec-66976fad12fa.png">

Notice for "Baila Wan", the last character of the Traditional Chinese is listed as a "geographic feature", however the source row of "Baila Wan" is the Simplified Chinese (the value in NAME_LINK), so it is true that if we only consider transliteration pairs we need to handle Romanization word segmentation.

**Comment by ronaldtse** [comment]
Closed in favor of #200.
