### ISSUE TITLE
Add UN Amharic transliteration 1967 system

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#390]
Originally from the Imperial Ethiopian Mapping and Geography Institute.

See http://www.eki.ee/wgrs/rom1_am.htm for spec.

Original spec: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/2nd-uncsgn-docs/E_Conf61_4_Add1_e.pdf
<img width="706" alt="Screen Shot 2020-09-08 at 1 11 05 PM" src="https://user-images.githubusercontent.com/11865/92435384-c2b19480-f1d4-11ea-8252-21d9160cf1c4.png">
<img width="700" alt="Screen Shot 2020-09-08 at 1 11 22 PM" src="https://user-images.githubusercontent.com/11865/92435396-cc3afc80-f1d4-11ea-8130-4cb12c0d63c5.png">
<img width="697" alt="Screen Shot 2020-09-08 at 1 11 31 PM" src="https://user-images.githubusercontent.com/11865/92435407-d0ffb080-f1d4-11ea-9c4d-666f02d0f649.png">
<img width="713" alt="Screen Shot 2020-09-08 at 1 12 21 PM" src="https://user-images.githubusercontent.com/11865/92435451-ef65ac00-f1d4-11ea-9eda-d4444a1c1c96.png">

Original spec PDF: [E_Conf61_4_Add1_e.pdf](https://github.com/interscript/interscript/files/5186160/E_Conf61_4_Add1_e.pdf)

**Comment by ronaldtse** [comment]
For @tsega

**Comment by ronaldtse** [comment]
@tsega can you confirm this is implemented in #414  ? Thanks!

**Comment by tsega** [comment]
@ronaldtse I can confirm that the #414 implements **Table 2. Amharic-to-English transliteration system of the Imperial Ethiopian Mapping and Geography Institute** shown above.

**Comment by ronaldtse** [comment]
Thank you @tsega! Closing this.
