### ISSUE TITLE
Add UN Romanization of Hindi version un-hin-deva-latn-2016

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#407]
Add:

un-hin-deva-latn-2016
UN Romanization of Hindi version 4.0
`un,iso-639-2,hin,Deva,Latn,2016,UN Romanization of Hindi version 4.0,,,2016-03-30`

**Comment by bilashsaha** [comment]
Ref Doc : 
https://www.eki.ee/wgrs/rom1_hi.pdf
https://www.eki.ee/wgrs/rom1_hi.htm

**Comment by bilashsaha** [comment]
PR : https://github.com/interscript/interscript/pull/428

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
