### ISSUE TITLE
Add UN Romanization of Marathi version 4.0 `un-mar-deva-latn-2016`

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#408]
un-mar-deva-latn-2016,UN Romanization of Marathi version 4.0,un,iso-639-2,mar,Deva,Latn,2016,UN Romanization of Marathi version 4.0,,,2016-03-30

**Comment by bilashsaha** [comment]
Ref Doc : https://www.eki.ee/wgrs/rom1_mr.pdf

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/428

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
