### ISSUE TITLE
Implement Devanagari Hunterian system (Hindu, Marathi)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#410]
var-hin-deva-latn-hunterian-1872,Hindu Devanagari Hunterian System,var,iso-639-2,hin,Deva,Latn,hunterian-1872,Hunterian System,,,
var-mar-deva-latn-hunterian-1872,Marathi Devanagari Hunterian System,var,iso-639-2,mar,Deva,Latn,hunterian-1872,Hunterian System,,,

**Comment by bilashsaha** [comment]
@ronaldtse for Hunterian system, upon researching, I found two reference 

1. https://transliteration.eki.ee/pdf/Hindi-Marathi-Nepali.pdf and 
2. https://en.wikipedia.org/wiki/Hunterian_transliteration

In the the first source the mapping is called Hunterian(3.0) and the wikipedia does not give any version or something. But the transliteration are little different in both of them for corresponding characters. Which source I should follow?

**Comment by ronaldtse** [comment]
The Hungarian system noted in Ref 1 has a (3.0), which refers to this:
<img width="768" alt="Screen Shot 2020-09-21 at 10 56 48 PM" src="https://user-images.githubusercontent.com/11865/93782934-bbbb6500-fc5d-11ea-9721-3259e711a0a7.png">

Let's follow the first one for now. Thanks!

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/462

**Comment by bilashsaha** [comment]
@ronaldtse We should close this one as the PR is merged

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
