### ISSUE TITLE
Add IAST 1912 Devanagari systems (Prakit, Sanskrit)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#411]
var-pra-deva-latn-iast-1912,IAST Prakit Devanagari System,var,iso-639-2,pra,Deva,Latn,iast-1912,<<IAST1912>>,,,
var-san-deva-latn-iast-1912,IAST Sanskrit Devanagari System,var,iso-639-2,san,Deva,Latn,iast-1912,<<IAST1912>>,,,

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/461
