### ISSUE TITLE
Implement ALA-LC Devanagari systems

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#412]
alalc-asm-deva-latn-2012,ALA-LC Romanization Table -- Assamese (2012),alalc,iso-639-2,asm,Deva,Latn,2012,ALA-LC Romanization Table -- Assamese (2012),,,2012
alalc-hin-deva-latn-2011,ALA-LC Romanization Table -- Hindi (2011),alalc,iso-639-2,hin,Deva,Latn,2011,ALA-LC Romanization Table -- Hindi (2011),,,2011
alalc-mar-deva-latn-2011,ALA-LC Romanization Table -- Marathi (2011),alalc,iso-639-2,mar,Deva,Latn,2011,ALA-LC Romanization Table -- Marathi (2011),,,2011
alalc-pli-deva-latn-2012,ALA-LC Romanization Table -- Pali (2012) -- Devanagari,alalc,iso-639-2,pli,Deva,Latn,2012,ALA-LC Romanization Table -- Pali (2012) -- Devanagari,,,2012
alalc-pra-deva-latn-2012,ALA-LC Romanization Table -- Sanskrit and Prakrit (2012),alalc,iso-639-2,pra,Deva,Latn,2012,ALA-LC Romanization Table -- Sanskrit and Prakrit (2012),,,2012
alalc-san-deva-latn-2012,ALA-LC Romanization Table -- Sanskrit and Prakrit (2012),alalc,iso-639-2,san,Deva,Latn,2012,ALA-LC Romanization Table -- Sanskrit and Prakrit (2012),,,2012

**Comment by bilashsaha** [comment]
PR : https://github.com/interscript/interscript/pull/457

**Comment by bilashsaha** [comment]
@ronaldtse We should close this one as the PR is merged

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
