### ISSUE TITLE
Implement DIN 33904 Devanagari to Latn/German systems

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#413]
din-hin-deva-latn-33904-2018,DIN 33904:2018 Information and documentation -- Romanization Devanagari (2018-10),din,iso-639-2,hin,Deva,Latn,33904-2018,<<DIN33904>>,,,
din-mar-deva-latn-33904-2018,DIN 33904:2018 Information and documentation -- Romanization Devanagari (2018-10),din,iso-639-2,mar,Deva,Latn,33904-2018,<<DIN33904>>,,,
din-nep-deva-latn-33904-2018,DIN 33904:2018 Information and documentation -- Romanization Devanagari (2018-10),din,iso-639-2,nep,Deva,Latn,33904-2018,<<DIN33904>>,,,
din-pli-deva-latn-33904-2018,DIN 33904:2018 Information and documentation -- Romanization Devanagari (2018-10),din,iso-639-2,pli,Deva,Latn,33904-2018,<<DIN33904>>,,,
din-pra-deva-latn-33904-2018,DIN 33904:2018 Information and documentation -- Romanization Devanagari (2018-10),din,iso-639-2,pra,Deva,Latn,33904-2018,<<DIN33904>>,,,
din-san-deva-latn-33904-2018,DIN 33904:2018 Information and documentation -- Romanization Devanagari (2018-10),din,iso-639-2,san,Deva,Latn,33904-2018,<<DIN33904>>,,,

**Comment by ronaldtse** [comment]
DIN 33904 | 2018-10 | Information und Dokumentation - Transliteration Devanagari : Information and documentation – Romanization Devanagari | Deva | Latn | san pra pli hin mar nep
-- | -- | -- | -- | -- | --

**Comment by ronaldtse** [comment]
Details can be found here: https://github.com/interscript/interscript-private-references/tree/master/din

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/464

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
