### ISSUE TITLE
Add tests for `un-mon-Mong-Latn-2013` Mongolian

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#415]
Right now we only have one test:

https://github.com/interscript/interscript/blob/fdc760394f0b7446e3b96d76ab5ad28b0bd06e67/maps/un-mon-Mong-Latn-2013.yaml#L42-L44

We need to add a lot more tests for this system.

**Comment by ronaldtse** [comment]
Related to #37

**Comment by ronaldtse** [comment]
And the original test quoted isn't even from the system; it's an example for #482  😭

**Comment by javkhaanj7** [comment]
@ronaldtse I'll change all of examples by pinyin version by checking wiki links that I used in the PR. If example's pinyin translation not found then I'll remove it
![image](https://user-images.githubusercontent.com/3781718/94634916-f4190e00-0303-11eb-8880-6ebd570879fe.png)

**Comment by ronaldtse** [comment]
@javkhaanj7 thanks. You'll need to be careful because the Pinyin from Wikipedia may be different from the UN system... e.g. the tone marks on the Wikipedia pinyin does not exist in the UN system.

**Comment by javkhaanj7** [comment]
@ronaldtse sure. Also I'll research about official translate/convert Chinese to Pinyin system and will check each converted Pinyin characters by matching unicode for double confirms.

**Comment by ronaldtse** [comment]
Merged #477 . Thanks @javkhaanj7 !
