### ISSUE TITLE
bas-rus system not working on interscript.com

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#426]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/11865/93574949-9ca5a480-f9cb-11ea-8314-3a90de84e9f7.png">

The resulting system after clicking on `bas` is not even selected.

<img width="771" alt="Screen Shot 2020-09-18 at 4 26 31 PM" src="https://user-images.githubusercontent.com/11865/93575031-b6df8280-f9cb-11ea-9037-9c98a3d8764e.png">

Usually you get this:
<img width="792" alt="Screen Shot 2020-09-18 at 4 29 13 PM" src="https://user-images.githubusercontent.com/11865/93575334-19388300-f9cc-11ea-9f8f-4b786f574f99.png">

**Comment by webdev778** [comment]
![image](https://user-images.githubusercontent.com/28761746/98112194-c1eb6500-1edc-11eb-8e63-0b0609a033f5.png)

**Comment by webdev778** [comment]
Fixed
