### ISSUE TITLE
Implement ISO 9984 Georgian

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#434]
http://transliteration.eki.ee/pdf/Georgian.pdf

**Comment by ronaldtse** [comment]
[ISO-9984-1996.pdf](https://github.com/interscript/interscript/files/5249220/ISO-9984-1996.pdf)

**Comment by ronaldtse** [comment]
<img width="580" alt="Screen Shot 2020-09-19 at 3 20 33 PM" src="https://user-images.githubusercontent.com/11865/93661614-aabafa00-fa8b-11ea-9245-d20c183dd69f.png">
<img width="556" alt="Screen Shot 2020-09-19 at 3 20 40 PM" src="https://user-images.githubusercontent.com/11865/93661615-ae4e8100-fa8b-11ea-962e-9f9a5b0a677c.png">
<img width="522" alt="Screen Shot 2020-09-19 at 3 20 47 PM" src="https://user-images.githubusercontent.com/11865/93661620-b27a9e80-fa8b-11ea-8094-45865077c403.png">

**Comment by ronaldtse** [comment]
Ping @antonsviridenko would you have time for this? Thanks!

**Comment by antonsviridenko** [comment]
ok

**Comment by ronaldtse** [comment]
Thanks @antonsviridenko !
