### ISSUE TITLE
Implement ISO/TR 11941:1996 Korean Romanization system

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#437]
[SIST-TP-ISO-TR-11941-2005.pdf](https://github.com/interscript/interscript/files/5249244/SIST-TP-ISO-TR-11941-2005.pdf)
[ISO-TR-11941-1996.pdf](https://github.com/interscript/interscript/files/5249245/ISO-TR-11941-1996.pdf)

**Comment by ronaldtse** [comment]
https://www.eki.ee/wgrs/rom2_ko.pdf

**Comment by webdev778** [comment]
PR #463

**Comment by ronaldtse** [comment]
There's also this document:
http://std.dkuug.dk/jtc1/sc2/wg2/docs/n2918.pdf
[n2918.pdf](https://github.com/interscript/interscript/files/5266448/n2918.pdf)

**Comment by ronaldtse** [comment]
For reference this is a partial extract of 11941: http://asadal.cs.pusan.ac.kr/~gimgs0/hangeul/rom/ts11941/index.html

**Comment by ronaldtse** [comment]
Implemented in #463
