### ISSUE TITLE
Provide option to give space between each transliterated segment in `hk-yue-Han-Latn-govt`, remove trailing space from map characters

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#44]
In the `hk-yue-Han-Latn-govt` system:

Each character is transliterated with a space to the next character. The last character of a phrase should not have a trailing space.

This task is to implement the option of providing a space after each transliterated character.

_Originally posted by @ronaldtse in https://github.com/riboseinc/interoperable-transliteration/pull/40#issuecomment-571648757_

**Comment by ronaldtse** [comment]
@abunashir , do you have time to look into this issue? The key is to create an option in maps to allow separating each character with a delimiter (e.g. a space). Thanks!

**Comment by abunashir** [comment]
@ronaldtse: This should be resolved by the attached PR.
