### ISSUE TITLE
Show statistics

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#440]
1. Number of languages supported
2. Number of source scripts, number of target scripts
3. Total number of rules in interscript

4. Number of script authorities
  * Number of conversion systems per authority (e.g. ODNI => 16)
  * Number of rules per authority

Interesting facts
* Which system has the most rules
* Which script authority has the most systems
* Which language has the most systems
* Which source/target script has the most systems

This should be implemented in the interscript gem and the CLI (`interscript stats`).

**Comment by webdev778** [comment]
#748 748
