### ISSUE TITLE
Issues in bgnpcgn-prs-Arab-Latn-2007

### ISSUE THREAD

**Issue by AhMohsen46** [interscript/interscript-ruby#442]
1.

a) in the following examples, `و` is transliterated to `ō` :

![image](https://user-images.githubusercontent.com/34799755/93690468-0cee1c00-fad9-11ea-9ac8-654530dc3462.png)
![image](https://user-images.githubusercontent.com/34799755/93690482-36a74300-fad9-11ea-8f77-97945f77bacc.png)

In this example it's also `ō`, but the damma is omitted:
![image](https://user-images.githubusercontent.com/34799755/93690535-b0d7c780-fad9-11ea-9163-626e7d72cb35.png)

However, in this example, it's `ū`:
![image](https://user-images.githubusercontent.com/34799755/93690487-4d4d9a00-fad9-11ea-99a8-be3a29ce34fe.png)

And in this example it's `w`:
![image](https://user-images.githubusercontent.com/34799755/93690517-8dad1800-fad9-11ea-88fd-d76b6bf7d4de.png)

May I ask if these examples have the right diacritical? And if yes, what's the rule followed here?
 
b) fatha followed by waw ` ـَو `. 

The rules says it should be transliterated to `ow` in Romanization:
![image](https://user-images.githubusercontent.com/34799755/93710129-7eaf7f80-fb44-11ea-8683-d2f05c902529.png)

But in this example, it's `aw`:
![image](https://user-images.githubusercontent.com/34799755/93710111-5e7fc080-fb44-11ea-9de4-5c627e0f3844.png)

Are the examples following Romanization or Yaghoubi?

2. 

a) For `ي` is it `\u064a` or `\06CC` in standard words?

b) In the following examples, what's the difference that makes `ي` transliterated to `y` vs transliterated to `ī`?

Examples with `ī`:
![image](https://user-images.githubusercontent.com/34799755/93709714-c7653980-fb40-11ea-8871-4a5615c346bd.png)

![image](https://user-images.githubusercontent.com/34799755/93709721-dba93680-fb40-11ea-9b0b-d7470b2fb3af.png)

![image](https://user-images.githubusercontent.com/34799755/93709739-0f845c00-fb41-11ea-9644-b6c6e02d889c.png)

Examples with `y`:
![image](https://user-images.githubusercontent.com/34799755/93709735-fbd8f580-fb40-11ea-963d-a4767637fb81.png)

My best guess from what I see, is normal letters where ` َ  ` "fatha" is followed by ya' `ي` it's transliterated to `ī` 
But sometimes it's `y` when there is a certain diacritical on ya' , that might be missing in the document "like sokoon for example" ` ْ  `

c) I believe the encoding value of this letter is not correct `ىٰ` in the document it's `\u06cc` while it should be either `\u06cc` or `\u0649` followed by `\u0670` which is the "dagger alif"  on the "ya'"

![image](https://user-images.githubusercontent.com/34799755/93709848-1495db00-fb42-11ea-897a-10a827f364b2.png)

3. Generally for all the rules in "Table 2":

![image](https://user-images.githubusercontent.com/34799755/93722822-d0cec000-fb99-11ea-9e46-595a444c454e.png)
![image](https://user-images.githubusercontent.com/34799755/93722828-e2b06300-fb99-11ea-884e-9f3ae6b288ec.png)

A lot of them have more than one transliteration, while there is no clear statement of when to use each of them. Can this be any clearer please?

4. Is there a specific rule followed in capitalization?

5. Finally for yaghoubi, is there any source of examples I can use?, or should I create a set of examples of my own from the available Roman Script which is done using Romanization in the doc?

**Comment by AhMohsen46** [comment]
related PR https://github.com/interscript/interscript/pull/441

**Comment by ronaldtse** [comment]
Clarification sought from BGN.

**Comment by ronaldtse** [comment]
Clarification received, in this case we have two responses.

Response 1:

> Issue 1., where the "و' is transliterated as "ō" or "ū", as well as "ow" is a matter of understanding the pronunciation of those terms. This is a prime example of the challenges faced when you have a character, with a variety of transliterated values that depend on the word in its definition/pronunciation. This is not easily determined by a set of rules outside of following a set glossary/dictionary of terms.

> Issue 2., follows the same. Unless the names are vowel pointed in script (which we know is rare/nonexistent), it would be difficult to state a rule "where fatha (zebar, in Farsi) is followed by ی, the transliteration is "ay". In their example they had "ī" instead of "ay". A fatha represents the short vowel "a", I think the fatha was meant to be a kasra (zir), so in their example, it would make sense to in Arabic were a 'kasra' followed by "ی" is transliterated "ī".

> There is more than one transliteration (value) for several characters, which makes it difficult to apply a set rule since there are no set indicators as to which value to select unless there's an understanding of the native language and its terms.”

Response 2:

> The Persians have a saying, which, roughly translated, becomes “The repentance of the wolf is death.” In English, we have a similar expression: “A leopard cannot change its spots.” While both of these sayings equate to the same aphorism, there is a chasm between the meaning and the understanding of them that cannot be bridged by a simple transliteration system, or even by a translation system. You have to understand not just the language itself, but the history of the language, the culture, and the various things that are important to those varieties of peoples that populate the earth. I don’t know that I can put into words how involved that process would be, without spending an unusually large amount of time doing so, but I hope that this somewhat poetic attempt at explaining things does a sufficient job of it.

**Comment by AhMohsen46** [comment]
issue 1/3: one more highlight of getting a glossary ready very soon for Farsi as well as arabic 
issue 2: yes!, it makes perfect sense that the fatha is a kasra, will checkout the glossary -- updating in PR https://github.com/interscript/interscript/pull/647

I will try to read more about persian next week, maybe this will be helpful gathering data and building a good glossary for our purpose

Thanks @ronaldtse !

**Comment by ronaldtse** [comment]
Thanks @AhMohsen46 !
