### ISSUE TITLE
Implement ISO 233-3 Arabic/Persian simplified transliteration to Latn

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#450]
ISO 233-3
Information and documentation — Transliteration of Arabic characters into Latin characters — Part 3: Persian language — Simplified transliteration

https://web.archive.org/web/20200920064754/http://www.freeprotocols.org/content/republished/doc.public/standards/communication/iso/iso-233/iso-233-3.pdf

http://www.freeprotocols.org/content/republished/doc.public/standards/communication/iso/iso-233/iso-233-3.pdf

**Comment by AhMohsen46** [comment]
@ronaldtse this https://github.com/interscript/interscript/pull/492 is done, except for shadda, and different transliteration for the same letter mentioned here https://github.com/interscript/interscript/issues/500

**Comment by ronaldtse** [comment]
Thank you @AhMohsen46 ! Closing this now.
