### ISSUE TITLE
Implement ISO 233-2 Arab to Latn "Simplified transliteration"

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#451]
https://cdn.standards.iteh.ai/samples/4118/2f03c828842c4055a5619c1bded39381/ISO-233-2-1993.pdf

[ISO-233-2-1993.pdf](https://github.com/interscript/interscript/files/5251236/ISO-233-2-1993.pdf)

<img width="469" alt="Screen Shot 2020-09-20 at 2 59 10 PM" src="https://user-images.githubusercontent.com/11865/93705696-d9030d00-fb51-11ea-87cb-2f1506d020fb.png">
<img width="471" alt="Screen Shot 2020-09-20 at 2 59 18 PM" src="https://user-images.githubusercontent.com/11865/93705698-dbfdfd80-fb51-11ea-92f1-097369dda1e9.png">
<img width="465" alt="Screen Shot 2020-09-20 at 2 59 31 PM" src="https://user-images.githubusercontent.com/11865/93705701-e3bda200-fb51-11ea-90f8-cb437ec67b28.png">
<img width="473" alt="Screen Shot 2020-09-20 at 2 59 37 PM" src="https://user-images.githubusercontent.com/11865/93705703-e7e9bf80-fb51-11ea-9773-c3c4e646f0d8.png">
<img width="469" alt="Screen Shot 2020-09-20 at 2 59 44 PM" src="https://user-images.githubusercontent.com/11865/93705704-ec15dd00-fb51-11ea-8c1b-93775024a46d.png">

**Comment by AhMohsen46** [comment]
looks like a quick win, getting it done now
