### ISSUE TITLE
Implement DIN 33903 Tamil to Latn/German

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#456]
DIN 33903 | 2016-02 | Information und Dokumentation - Umschrift Tamil : Information and documentation – Romanization of Tamil | Taml | Latn | tam
-- | -- | -- | -- | -- | --

**Comment by ronaldtse** [comment]
4 principles of transcription
Since the Tamil script is a syllabic script, the consonant -a inherent in the transliteration is always written, even in the final.

A point above the consonant, the so-called "pulli", means in Tamil that the inherent -a is omitted:

<img width="143" alt="Screen Shot 2020-09-22 at 6 06 36 PM" src="https://user-images.githubusercontent.com/11865/93869433-5e2b2500-fcfe-11ea-8beb-1b78245a0c23.png">

Tamil has no anusvara; in contrast to other South Asian scripts, the class nasal is always written.

Tamil also has no ligatures.


5 translation tables
The following tables 1 to 3 show the transliteration for Tamil vowels, consonants and digits.

<img width="440" alt="Screen Shot 2020-09-22 at 6 07 08 PM" src="https://user-images.githubusercontent.com/11865/93869494-700cc800-fcfe-11ea-9463-02b8a6ce47c1.png">

a) 2a to 12a represent the vowels as they are written in conjunction with consonants. The dashed circle stands as a placeholder for the respective consonant.

<img width="430" alt="Screen Shot 2020-09-22 at 6 07 54 PM" src="https://user-images.githubusercontent.com/11865/93869570-8adf3c80-fcfe-11ea-8a4b-5fc325576b63.png">

b) The letter is required for Sanskrit loanwords and appears in the transliteration table of the Tamil lexicon, but not in the lexicon itself. In practice, ஷ is used for all "sh" sounds; in the transliteration, however, Sanskrit differentiates correctly between śa and ṣa

<img width="436" alt="Screen Shot 2020-09-22 at 6 08 22 PM" src="https://user-images.githubusercontent.com/11865/93869610-9fbbd000-fcfe-11ea-8b43-6c8976f94c97.png">

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/466

**Comment by bilashsaha** [comment]
@ronaldtse We should close this one as the PR is merged

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
