### ISSUE TITLE
Mechanism that converts between two transliteration systems

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#465]
Currently Interscript allows "source script =(system A)=> transliterated script".

This ticket is to implement "transliterated script from system A => transliterated script from system B". This presumably depends on whether:

* "transliterated script from system A => transliterated script from system B" works directly
* "transliterated script from system A => reverse transliterated original script => transliterated script from system B" works

Here's an example:
* http://roman.cs.pusan.ac.kr/eng_result_MR1.aspxhttp://roman.cs.pusan.ac.kr/input_eng.aspx

<img width="439" alt="Screen Shot 2020-09-23 at 7 19 14 PM" src="https://user-images.githubusercontent.com/11865/94005960-ae26ec00-fdd1-11ea-9483-9eb6e81d2f2e.png">

This gets generated:

<img width="436" alt="Screen Shot 2020-09-23 at 7 18 54 PM" src="https://user-images.githubusercontent.com/11865/94005922-9fd8d000-fdd1-11ea-85a9-2c79cc4135be.png">

**Comment by ronaldtse** [comment]
In the second case, we can use a pivot system to convert scripts across a pair of scripts that have a common convertible system but not a direct system.

**Comment by webdev778** [comment]
After merging reversibility (planned for today), we will be able to do it in such a form:

```ruby
dependency "var-kor-Latn-Hang-revised", as: latnhang # Where there is a map "var-kor-Hang-Latn-revised", by reversing the character sets in the name, we depend on a reversed map
dependency "var-kor-Hang-Latn-mccune", as: hanglatn

stage {
  run latnhang # run "var-kor-Hang-Latn-revised" in reverse
  run hanglatn # run "var-kor-Hang-Latn-mccune" in forward
}
```

Do we need something more? We can use a name like "var-kor-Latn-Hang-revised|var-kor-Hang-Latn-mccune" that would be recognized whenever a map name appears (ie. in CLI tool)

**Comment by webdev778** [comment]
Both scenarios are implemented by this commit.

**Comment by ronaldtse** [comment]
Thanks @webdev778 ! Ping @ribose-jeffreylau on the method of reversing transliteration systems.

**Comment by ribose-jeffreylau** [comment]
Hi @webdev778 , this will be related to https://github.com/interscript/spelling-systems-data/issues/1 but for now, what is seen here looks fine.  Thanks!

**Comment by ronaldtse** [comment]
@webdev778 there are Latn to Latn systems which this scheme will present a problem.

In the next few weeks though @ribose-jeffreylau will detail the changes to the code — the spelling system code (a new code) will replace the script code, so the Latn-Latn problem will disappear.

**Comment by webdev778** [comment]
It won't. In such a case the reversed map is named by appending `-reverse`.

**Comment by ronaldtse** [comment]
@webdev778 that's great -- can we make sure that's documented? Thanks!

**Comment by ronaldtse** [comment]
@webdev778 it looks like we need a method to dynamically write scripts for Interscript, e.g.

CLI:
```sh
interscript \
  --dependency "latnhang=var-kor-Latn-Hang-revised" \
  --dependency "hanglatn=var-kor-Hang-Latn-mccune" \
  --pipeline "run map.latnhang.stage.main; run map.hanglatn.stage.main"
  my_input.txt
```

Thoughts?

**Comment by webdev778** [comment]
It is documented, yes.

Also, while it could be nice addition to the CLI to generate maps on demand, this particular case can be written this way:

```ruby
interscript my_file.txt \
  --system='var-kor-Latn-Hang-revised|var-kor-Hang-Latn-mccune' \
  --output=my_output.txt
```

**Comment by ronaldtse** [comment]
The syntax makes sense with `|` like the pipe. I like it.

**Comment by webdev778** [comment]
PR #731
