### ISSUE TITLE
Fix minor translate issue in BGN_Romanization_Guide_1964_mongolian_1964.pdf doc

### ISSUE THREAD

**Issue by javkhaanj7** [interscript/interscript-ruby#468]
**dz** romanize should be just **z** for з character

BGN_Romanization_Guide_1964_mongolian_1964.pdf can be found in https://github.com/interscript/interscript/issues/139

**Comment by ronaldtse** [comment]
@javkhaanj7 according to the latest 2019 version of the BGN 1964 system, it is still `dz`:
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/816781/ROMANIZATION_OF_MONGOLIAN.pdf

<img width="552" alt="Screen Shot 2020-09-28 at 11 58 08 AM" src="https://user-images.githubusercontent.com/11865/94389230-e176cb80-0181-11eb-8656-1a081ba65b5e.png">

Where do you see it should be `z` for `з`? Is this from another Mongolian system?

**Comment by javkhaanj7** [comment]
@ronaldtse `dz` is for IPA (phonetic notation) of `з`. We have to use `z` instead 'dz' for the romanization translate

![image](https://user-images.githubusercontent.com/3781718/94390216-a1651800-0184-11eb-8a1b-f782ef61cd8c.png)

More reference links:
https://en.wikipedia.org/wiki/Mongolian_Latin_alphabet
https://en.wikipedia.org/wiki/Mongolian_Cyrillic_alphabet

**Comment by ronaldtse** [comment]
I believe the BGN system is correct in itself. The `z` character is used in other systems, but not in BGN's system, so we can close this.
