### ISSUE TITLE
Test against Geonames data (Taiwan)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#47]
Uses zho_Hani2Latn_AcadSin_2002 and zho_Hani2Latn_WDG_1987, need definition of them.

This data set does work with Pinyin.

[tw.zip](https://github.com/riboseinc/interoperable-transliteration/files/4031744/tw.zip)

On #41 , notice that the rows with zho_Hani2Latn_WDG_1987 do not have NAME_LINK back to the Chinese characters, so in building the map we need to find the Chinese character line and link it to zho_Hani2Latn_WDG_1987 output.

**Comment by chaaklau** [comment]
This attached book is published by Academia Sinica and has a table that compares different transliteration schemes for Taiwan Mandarin. 

zho_Hani2Latn_WDG_1987 (Chinese Wade-Giles 1979 System)
zho_Hani2Latn_AcadSin_2002 (Chinese Tongyong Pinyin Academia Sinica 2002 System)

[漢字拼音討論集.pdf](https://github.com/riboseinc/interoperable-transliteration/files/4034159/default.pdf)

**Comment by chaaklau** [comment]
I tried joining NAME_LINK and UNI columns, and found that 
**zho_Hani2Latn_WDG_1987** in the tw data does not have NAME_LINK

![image](https://user-images.githubusercontent.com/5143421/72075753-545bc000-332f-11ea-929c-07d74d3776b5.png)

So I used *MGRS* to group the data, and extracted TC <-> WDG pairs for testing.
[tw_wdg.txt](https://github.com/riboseinc/interoperable-transliteration/files/4041568/tw_wdg.txt)

----

I used the dataset from [https://data.gov.tw/dataset/5961] for character pronunciations. One limitation with this dataset is that when a character has multiple pronunciations, the order provided does not reflect actual frequency. 

I am going to use tw_wdg.txt (extracted from GeoNames) to generate a frequency map to improve the character to pronunciation map.

**Comment by ronaldtse** [comment]
@chaaklau I've also done some experiments in the China dataset with joining NAME_LINK and UNI; what I realized was that many rows lack TRANSL_CD. In the HK dataset, I think there were only 4 rows...

In terms of transliteration maps I think the way to go is something like this: https://arxiv.org/abs/1610.09565 . That would be a further subject.

**Comment by ronaldtse** [comment]
@chaaklau all the transliteration pairs that have transliteration systems are now at https://github.com/riboseinc/geonames-transliteration-data/releases/tag/v1.0 !

**Comment by ronaldtse** [comment]
Closing for #199 .
