### ISSUE TITLE
Implement Mongolian MNS 5217:2012 for Latin Characters

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#480]
Codes:
- `mns-mon-Cyrl-Latn-5217-2012` (Cyrillic to Latin)
- `mns-mon-Latn-Cyrl-5217-2012` (Latin to Cyrillic)

Official spec:
- http://estandard.gov.mn/standard/v/4635
- read here: http://estandard.gov.mn/standard/reader/4635

Useable spec: 
- https://fr.wikipedia.org/wiki/MNS_5217:2012
- http://batsaikhan.mn/монгол-кирил-үсгийн-латин-хөрвүүлэг-mns-52172012-стандарт-батлагдлаа/

**Comment by javkhaanj7** [comment]
@ronaldtse could you add "mns" prefix in filenames_spec.rb for the file name check test?

Below file names need to pass in the test:

```
mns-mon-Cyrl-Latn-5217-2012
mns-mon-Latn-Cyrl-5217-2012
```

Current error:
```
1) filenames name mns-mon-Cyrl-Latn-5217-2012 is valid?
     Failure/Error: expect(valid_authcodes).to include authcode
       expected ["acadsin", "ahl", "alalc", "ammi", "ansi", "apcbg", "asm", "az", "bas", "bds", "bgn", "bgna", "bgnpc...es", "sfs", "sgk", "tm", "ua", "ucis", "un", "uz", "var", "xlsc", "yivo", "mvd", "stategeocadastre"] to include "mns"
     # ./spec/interscript/filenames_spec.rb:378:in `block (3 levels) in <top (required)>'
```

**Comment by ronaldtse** [comment]
@javkhaanj7 could you add it directly? Thanks.

**Comment by javkhaanj7** [comment]
@ronaldtse can we close the issue?

**Comment by ronaldtse** [comment]
Thanks @javkhaanj7 !
