### ISSUE TITLE
Implement var-mon-Mong-Latn-vpmc

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#482]
Mostaert-Vladimirtsov system in:
https://collab.its.virginia.edu/wiki/tibetan-script/Transliteration%20Schemes%20for%20Mongolian%20Vertical%20Script.html

https://fr.wikipedia.org/wiki/Translittération_VPMC

**Comment by javkhaanj7** [comment]
@ronaldtse I think it's duplicate of alalc-mon-mong-latn-1997 which issued in https://github.com/interscript/interscript/issues/384. Because it's pointing same document https://www.loc.gov/catdir/cpso/romanization/mongolia.pdf

**Comment by ronaldtse** [comment]
The system is column 1, the Ala-LC system is column 3.

**Comment by ronaldtse** [comment]
Merged #518. Thanks @javkhaanj7 !
