### ISSUE TITLE
Implement Persian [UN 1967, I/13]

### ISSUE THREAD

**Issue by AhMohsen46** [interscript/interscript-ruby#489]
Implement map for Persian UN 1967 as requested in https://github.com/interscript/interscript/issues/488

doc url: http://www.eki.ee/wgrs/v2_2/rom1_fa.htm

**Comment by ronaldtse** [comment]
@AhMohsen46 FYI the other Persian systems are: ALALC in #94, BGNPCGN in #96 , ODNI in #98 and #288 , DIN in #447, ISO in #450

**Comment by ronaldtse** [comment]
This system is also available in https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/2nd-uncsgn-docs/E_Conf61_L5_Add12.pdf (see the "IRAN" column)

<img width="1016" alt="Screen Shot 2020-09-29 at 8 02 31 PM" src="https://user-images.githubusercontent.com/11865/94555803-b62dd280-028e-11eb-94bf-d0608402fd10.png">

**Comment by AhMohsen46** [comment]
is this https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/2nd-uncsgn-docs/E_Conf61_L5_Add12.pdf
equivalent to this http://www.eki.ee/wgrs/v2_2/rom1_fa.htm?

**Comment by ronaldtse** [comment]
@AhMohsen46 I believe you're right, they are identical.

**Comment by AhMohsen46** [comment]
this is almost identical https://github.com/interscript/interscript/issues/96

except for a very very few differences which are in this doc  https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/2nd-uncsgn-docs/E_Conf61_L5_Add12.pdf in the second/third columns

**Comment by AhMohsen46** [comment]
done here https://github.com/interscript/interscript/pull/568
please check the properties in the beginning of the file

concerns https://github.com/interscript/interscript/issues/569
