### ISSUE TITLE
Implement Urdu [UN 1972, II/11; 1977, III/12]

### ISSUE THREAD

**Issue by AhMohsen46** [interscript/interscript-ruby#490]
as requested in https://github.com/interscript/interscript/issues/488
doc url: https://www.eki.ee/wgrs/rom1_ur.htm

**Comment by ronaldtse** [comment]
The original spec is available here: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/2nd-uncsgn-docs/E_Conf61_L5_Add8.pdf

**Comment by AhMohsen46** [comment]
done in https://github.com/interscript/interscript/pull/583
