### ISSUE TITLE
Implement `un-ell-Grek-Latn-ipa-1987` Greek to IPA

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#534]
From E/CONF.79/INF/38

<img width="622" alt="Screen Shot 2020-10-08 at 12 06 26 PM" src="https://user-images.githubusercontent.com/11865/95413723-b13be380-095e-11eb-9015-ba6f7ab7e7e2.png">
[e_conf_79_inf38.pdf](https://github.com/interscript/interscript/files/5345248/e_conf_79_inf38.pdf)

**Comment by andrew2net** [comment]
@ronaldtse does this [document](https://www.eki.ee/wgrs/v2_2/rom1_el.htm) describe the `un-ell-Grek-Latn-ipa-1987` system?

**Comment by ronaldtse** [comment]
Actually this system was already implemented here: https://github.com/interscript/maps/blob/master/maps/un-ell-Grek-Latn-1987-phonetic.imp

Sorry about that. Thanks!
