### ISSUE TITLE
Implement system `alalc-pan-Guru-Latn-2011` (ALA-LC Romanization Table -- Panjabi (2011)

### ISSUE THREAD

**Issue by bilashsaha** [interscript/interscript-ruby#537]
This issue is to implement the transliteration system of alalc-pan-Guru-Latn-2011.

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/546

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
