### ISSUE TITLE
Implement system `alalc-guj-Gujr-Latn-2011` (ALA-LC Romanization Table -- Gujarati  (2011)

### ISSUE THREAD

**Issue by bilashsaha** [interscript/interscript-ruby#538]
This issue is to implement the transliteration system of alalc-guj-Gujr-Latn-2011.

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/547

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
