### ISSUE TITLE
Implement system `alalc-guj-Gujr-Latn-1997` (ALA-LC Romanization Table -- Gujarati (1997)

### ISSUE THREAD

**Issue by bilashsaha** [interscript/interscript-ruby#539]
This issue is to implement the transliteration system of alalc-guj-Gujr-Latn-1997.

**Comment by ronaldtse** [comment]
Spec: http://catdir.loc.gov/catdir/cpso/romanization/gujarati.pdf

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/547

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
