### ISSUE TITLE
concerns in un-prs-Arab-Latn-1967

### ISSUE THREAD

**Issue by AhMohsen46** [interscript/interscript-ruby#569]
1st-is there any specific rule for ta' marboota?
2-a)in this rule, يه is īyeh, is it missing any pointing?, shadda or kasrah?
b)should all sun letters be like "od din"?, with o instead of a?
also, does this mean that normal article definition will be with ol instead of al?
![image](https://user-images.githubusercontent.com/34799755/96337985-55263d00-108b-11eb-81dd-b5dc11e3102e.png)
Thanks!

**Comment by ronaldtse** [comment]
We’ve got clarification from UN:

> 1. Ta' marboota, as far as I understand, applies only to Arabic loanwords and I have the impression that it follows the same rules than in Arabic.

> 2a) The ending is without diacritical signs – which is common use in Persian –, otherwise it should contain both shaddah and kasrah.

> 2b) Don't know but I suppose yes.

Are we ready to proceed!

**Comment by AhMohsen46** [comment]
@ronaldtse yes sir, this clarifies all what I need, will push the required change for 2a along with https://github.com/interscript/interscript/pull/583

**Comment by ronaldtse** [comment]
Thanks @AhMohsen46 !

**Comment by AhMohsen46** [comment]
done in https://github.com/interscript/interscript/pull/583/commits
Thanks @ronaldtse !

**Comment by ronaldtse** [comment]
Thanks @AhMohsen46 !
