### ISSUE TITLE
Concerns in (BGN/PCGN Romanization System -- Urdu (2007) 

### ISSUE THREAD

**Issue by AhMohsen46** [interscript/interscript-ruby#572]
in #188 
in the following examples ي is transliterated to e
![image](https://user-images.githubusercontent.com/34799755/96363811-ca028100-1136-11eb-9bf1-95d78a218e10.png)
![image](https://user-images.githubusercontent.com/34799755/96363839-f9b18900-1136-11eb-9591-328538e0f049.png)
![image](https://user-images.githubusercontent.com/34799755/96363853-0df58600-1137-11eb-8331-cd651eef8f18.png)

although, it should be y as per the table here
![image](https://user-images.githubusercontent.com/34799755/96363871-21085600-1137-11eb-8351-2b07b721bb0f.png)

same for و it's transliterated to o, although in the table it's w
however, و got two rules, but am not sure which one to follow, as there is nothing special about any of them

examples:
و as o
![image](https://user-images.githubusercontent.com/34799755/96363907-6b89d280-1137-11eb-879b-ec6701c776dd.png)

و as w
![image](https://user-images.githubusercontent.com/34799755/96363916-865c4700-1137-11eb-8fd9-a00f75642963.png)

two rules:
w:
![image](https://user-images.githubusercontent.com/34799755/96363925-996f1700-1137-11eb-94fc-aeb71715b133.png)

o:
![image](https://user-images.githubusercontent.com/34799755/96363931-aab82380-1137-11eb-9df8-1ba8b8f229f5.png)

**Comment by ronaldtse** [comment]
Clarification sought from BGN.

**Comment by AhMohsen46** [comment]
@ronaldtse exact same issue in https://github.com/interscript/interscript/pull/25
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/693687/ROMANIZATION_OF_BALUCHI.pdf

**Comment by ronaldtse** [comment]
Received clarification from BGN.

> This is one of the examples where the developers will find huge challenges in working with abjad scripts (Arabic, Persian, Pashto, Urdu, Dari... ), where short vowels are unmarked, relying on a deeper knowledge of the language to understand how/where certain vowelings are applied. I find it more difficult to explain other than to suggest studying a list of Urdu terms to fully understand those spellings.
>
> Those unmarked short vowels will always be the biggest challenge to any automated transliteration tool, unless they ingest a full catalog/glossary of terms. For Persian, short vowels will differ across regions as well, where an "a" is used/pronounced instead of "e".

@AhMohsen46 hope this is of sufficient use. If we are able to apply proper pointing for this language, we may be able to automate this to acceptable quality.

The key here is, as suggested, to have a catalog/glossary of terms -- in fact, also sentences because context is important -- so a good training data set on Urdu. It's something to do in the future, perhaps.

**Comment by AhMohsen46** [comment]
@ronaldtse the more we create the systems, the more we discover the serious need of a glossary
speaking of which, I contacted a lot of linguistic researchers from different universities, but none was so lucky unfortunately
however, I will fully concentrate on this starting next week, since I'm going to be off for xmas vacation and I'll have plenty of time to get this done

**Comment by AhMohsen46** [comment]
assigning myself to reach later, and closing 
Thanks for your effort @ronaldtse !

**Comment by ronaldtse** [comment]
Thanks!
