### ISSUE TITLE
Clarify authority of `ses-ara-arab-latn-1930` Survey of Egypt Arabic System

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#59]

**Comment by AhMohsen46** [comment]
related PR https://github.com/interscript/interscript/pull/357
related issues https://github.com/interscript/interscript/issues/362 , https://github.com/interscript/interscript/issues/68

**Comment by AhMohsen46** [comment]
@ronaldtse I guess we can close this
