### ISSUE TITLE
BGN/PCGN Persian transliteration looking funny

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#593]
https://jsdemo.interscript.com/bgnpcgn

<img width="248" alt="image" src="https://user-images.githubusercontent.com/11865/97261949-ddaa9780-185a-11eb-95ff-1ab06e3c276c.png">

**Comment by AhMohsen46** [comment]
@ronaldtse sorry this happened
I've 2 questions please
1- is the original word here `اِيران` ?
I added two examples here https://github.com/interscript/interscript/pull/594, they look working to me
2-which file is used for 1956?
I think this one? https://github.com/interscript/interscript//blob/1fd40d06179b0af11cd4b7c4329f640a61718424/maps/bgnpcgn-fas-Arab-Latn-1956.yaml
if yes, this one is not ready yet
I've just also taken a look on the doc in the file https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/320079/Arabic_Romanization.pdf
it's for arabic, not `fas`
I think it might have been mistakenly used?
as it almost give me the same results as the one in 1956 in the screenshot above

 
![image](https://user-images.githubusercontent.com/34799755/97266098-855ea000-1830-11eb-816a-eeb716aacd91.png)

**Comment by AhMohsen46** [comment]
I also suspect this `fas` in the file mentioned in the previous comment should be `ara`
and this `ara` should be `fas` https://github.com/interscript/interscript/issues/60

**Comment by AhMohsen46** [comment]
should we close this?
@ronaldtse
