### ISSUE TITLE
Correct alalc-kan-Kana-Latn-2011

### ISSUE THREAD

**Issue by bilashsaha** [interscript/interscript-ruby#600]
Source : https://www.loc.gov/catdir/cpso/romanization/kannada.pdf
The year is wrong in this. It has to be `2011` insttead of `2012`

**Comment by ronaldtse** [comment]
Indeed, the PDF itself was created in 2011 :wink:

<img width="366" alt="Screen Shot 2020-11-03 at 9 19 40 AM" src="https://user-images.githubusercontent.com/11865/97936181-b6514e80-1db5-11eb-999f-08721816fffe.png">

**Comment by bilashsaha** [comment]
@ronaldtse PR is here : https://github.com/interscript/interscript/pull/603 and Its merged. We should close this issue.
