### ISSUE TITLE
Check whether these examples work with odni-ukr-Cyrl-Latn-2015

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#607]
From #305 we have these two examples.

Новофедірівка => Novofedorivka
Гуляйгородок => Hulyayhorodok

We want to know if they can be added to the `odni-ukr-Cyrl-Latn-2015` system:
https://github.com/interscript/interscript/blob/b7e4d2ec175a66bffcb20e2c5b0808bb4fe63404/maps/odni-ukr-Cyrl-Latn-2015.yaml#L2-L7

If so, add them as examples. Thanks!

**Comment by andrew2net** [comment]
> Новофедірівка => Novofedorivka

@ronaldtse this example fails because of "i" => "i" (not "o"). We could add special cases like this in the `characters` section as "Новофедірівка": "Novofedorivka"
What do you think?

**Comment by ronaldtse** [comment]
In this maybe the text doesn’t come from this system. Can you loop through the systems for ukr/Cyrl to see what system this text is generated from?

**Comment by andrew2net** [comment]
@ronaldtse it seems no one Ukr systems can transliterate Новофедірівка to Novofedorivka.
In [Wikipedia](https://en.wikipedia.org/wiki/Novofedorivka), it called Новофедорівка in Ukrainian. Furthermore, Новофедорівка is more used on the Internet then Новофедірівка (41000 vs 2000 results in Google). Maybe we should use Новофедорівка for testing, don't we?

**Comment by ronaldtse** [comment]
I will report the problem with (Новофедірівка to Novofedorivka).

How about Гуляйгородок => Hulyayhorodok ?

**Comment by andrew2net** [comment]
> How about Гуляйгородок => Hulyayhorodok ?

This test passes. I added it to this system.

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
