### ISSUE TITLE
Implement system `odni-prs-arab-latn-2004` (Office of the Director Of National Intelligence Dari Personal Names 2004 System)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#616]
Spec: https://github.com/interscript/interscript-private-references/blob/master/odni/Farsi_(Persian)_%26_Dari_IC_Standards.doc

_Originally posted by @ronaldtse in https://github.com/interscript/interscript/issues/98#issuecomment-722228053_

**Comment by AhMohsen46** [comment]
Working on this now

**Comment by AhMohsen46** [comment]
Done in https://github.com/interscript/interscript/pull/623, both systems
they are like 99% similar to https://github.com/interscript/interscript/pull/510
concerns are the exact same as https://github.com/interscript/interscript/issues/509
Thanks!
