### ISSUE TITLE
Implement system `alalc-amh-ethi-latn-1997` (ALA-LC Romanization Table -- Amharic (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#62]
This issue is to implement the transliteration system of alalc-amh-ethi-latn-1997.

This system is referred in the GeoNames database as `amh_Ethi2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Amharic (1997)'.

 Tests should rely on the data extracted for the `amh_Ethi2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Ping @tsega

**Comment by ronaldtse** [comment]
Spec: http://catdir.loc.gov/catdir/cpso/romanization/amharic.pdf
[amharic.pdf](https://github.com/interscript/interscript/files/5186108/amharic.pdf)

**Comment by tsega** [comment]
@ronaldtse the 6th order mapping has two values 
```
ህ  he or h
```
From my understanding it should simply be `he` as Amharic letters come with their vowels.

**Comment by tsega** [comment]
The data from the geonmaes-transliteration-data application in `pairs/amh_Ethi2Latn_ALA_1997.csv` seems to be incorrect

```
TRANSL_CD,LC,SRC_UNI,SRC_NT,SRC_FULL_NAME_RO,SRC_FULL_NAME_RG,DEST_UNI,DEST_NT,DEST_FULL_NAME_RO,DEST_FULL_NAME_RG
amh_Ethi2Latn_ALA_1997,rus,17892694,VS,"Ходорковцы","Ходорковцы",-3212374,V,Khodorkovtsy,Khodorkovtsy
```

**Comment by ronaldtse** [comment]
Completed, closing.
