### ISSUE TITLE
Implement UN Gujarati system [UN 1972, II/11; 1977, III/12] `un-guj-Gujr-Latn-1972`

### ISSUE THREAD

**Issue by bilashsaha** [interscript/interscript-ruby#653]
Source: https://www.eki.ee/wgrs/rom1_gu.htm

**Comment by ronaldtse** [comment]
ALALC 1997 done #99
ALALC 2011 done #538

**Comment by bilashsaha** [comment]
@ronaldtse PR: https://github.com/interscript/interscript/pull/679
