### ISSUE TITLE
Implement system `odni-ara-arab-latn-2004` (Arabic Personal Names Office of the Director Of National Intelligence 2004 System

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#66]
This issue is to implement the transliteration system of odni-ara-arab-latn-2004.

This system is referred in the GeoNames database as `ara_Arab2Latn_ODNI_2004`, with the system title 'Arabic Personal Names Office of the Director Of National Intelligence 2004 System'.

 Tests should rely on the data extracted for the `ara_Arab2Latn_ODNI_2004` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
We're going to skip all non-current ODNI systems for now. Closing this for now. Thanks!

**Comment by ronaldtse** [comment]
Reopening since we have spec now:
https://github.com/interscript/interscript-private-references/blob/master/odni/Arabic_IC_Standard.doc

**Comment by AhMohsen46** [comment]
next

**Comment by AhMohsen46** [comment]
Done in https://github.com/interscript/interscript/pull/646
