### ISSUE TITLE
Bump version of interscript gem

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#682]
Many new systems now available. @webdev778 can you help bump the gem? Thanks.

**Comment by webdev778** [comment]
sure

**Comment by webdev778** [comment]
I updated `release.yml` GHA withi this commit [74e27](https://github.com/interscript/interscript/commit/74e27867a8984ec580d26b22cbbf82d96ff5e3e3)

![image](https://user-images.githubusercontent.com/28761746/102309247-b4310100-3fab-11eb-9e2e-aaa35a243dca.png)

**Comment by ronaldtse** [comment]
Thanks @webdev778 ! Remaining work moved to ~~#684~~ #683.
