### ISSUE TITLE
Fix macOS builds with Ruby 2.5

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#689]
macOS Ruby 2.5 builds have been failing. Strangely it's the only combo that breaks.

**Comment by webdev778** [comment]
this issue is related to this [issue](https://github.com/ruby-debug/debase/issues/91)

**Comment by webdev778** [comment]
the problem was **debase** gem installing error on the latest macOSX since Nov 2020.
I recommend to remove a couple of gems of dependency from **gemspec**

- debase
- ruby-debug-ide
