### ISSUE TITLE
Implement system `alalc-asm-deva-latn-1997` (ALA-LC Romanization Table -- Assamese (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#69]
This issue is to implement the transliteration system of alalc-asm-deva-latn-1997.

This system is referred in the GeoNames database as `asm_Deva2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Assamese (1997)'.

 Tests should rely on the data extracted for the `asm_Deva2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/397

**Comment by ronaldtse** [comment]
Thanks @bilashsaha !
