### ISSUE TITLE
Implement system `alalc-aze-cyrl-latn-1997` (ALA-LC Romanization Table -- Azerbaijani (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#70]
This issue is to implement the transliteration system of alalc-aze-cyrl-latn-1997.

This system is referred in the GeoNames database as `aze_Cyrl2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Azerbaijani (1997)'.

 Tests should rely on the data extracted for the `aze_Cyrl2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
@ronaldtse here I have found the only version from 2017 https://www.loc.gov/catdir/cpso/roman.html

According to text on this page bellow:

> The 1997 edition of the tables is also available for purchase in book form from the Cataloging Distribution Service while supplies last.

Let me know if you have access to it

**Comment by ronaldtse** [comment]
The 1997 editions are available here: http://catdir.loc.gov/catdir/cpso/roman.html

**Comment by ronaldtse** [comment]
Hmm that site only contains the Arabic system not the Cyrillic system, but this is it:
https://transliteration.eki.ee/pdf/Azerbaijani.pdf

<img width="526" alt="Screen Shot 2020-05-28 at 10 04 40 AM" src="https://user-images.githubusercontent.com/11865/83090154-b2185b00-a0ca-11ea-9569-57bcce96e2dc.png">
<img width="528" alt="Screen Shot 2020-05-28 at 10 04 45 AM" src="https://user-images.githubusercontent.com/11865/83090156-b3e21e80-a0ca-11ea-9a09-3c36bfdf703a.png">
