### ISSUE TITLE
Reinstate GHA CI tests

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#706]
Somehow they were lost during the repo migration to v2.

This issue is to reinstate all the tests.

**Comment by ronaldtse** [comment]
From @CAMOBAP  (https://github.com/interscript/interscript/pull/704)

* windows blocked because sqreen/ruby-libv8-node#9
* macOS some tests failed will be investigated in the scope of #705

**Comment by webdev778** [comment]
Restored
