### ISSUE TITLE
Support option of returning best guess or all possible transliterations

### ISSUE THREAD

**Issue by ribose-jeffreylau** [interscript/interscript-ruby#714]
_Originally: https://github.com/interscript/lcs/issues/2#issuecomment-578096993_

**Comment by ronaldtse** [comment]
Premise:
- sometimes there are ambiguous conversion rules, such as 1 character converting to 1 out of 2 characters
- in these cases we currently only return the result for the 1st conversion, the 2nd+ rules are ignored

This issue requires implementation of an option to return either a single instance of the conversion result, or all instances of the results.

One can consider that the conversion result space can be:
* a single result (a-b-c) or
* a full set of results (a-{b,d}-c, which is a-b-c and a-d-c).

**Comment by webdev778** [comment]
Fixed [refer to here](https://github.com/interscript/interscript/blob/master/ruby/spec/transliterate_each_spec.rb)
