### ISSUE TITLE
Support specification of reverse script conversion

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#716]
One feature that we don't have is the indication of whether a rule can be reversed (bidirectional).

This feature is supported by Unicode's LDML. 

This is also related to the functionality described by #465, as a pivot point to convert scripts across a pair of scripts that have a common convertible system but not a direct system.

_Originally posted by @ronaldtse in https://github.com/interscript/interscript/issues/715#issuecomment-850078024_

**Comment by webdev778** [comment]
Implemented by #722

**Comment by ronaldtse** [comment]
Thanks! The next task for reversibility is #732
