### ISSUE TITLE
Implement system `bgnpcgn-bak-cyrl-latn-2007` (BGN/PCGN Table of Correspondences -- Bashkir (2007)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#72]
This issue is to implement the transliteration system of bgnpcgn-bak-cyrl-latn-2007.

This system is referred in the GeoNames database as `bak_Cyrl2Latn_BGN_2007`, with the system title 'BGN/PCGN Table of Correspondences -- Bashkir (2007)'.

 Tests should rely on the data extracted for the `bak_Cyrl2Latn_BGN_2007` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/829203/TABLE_OF_CORRESPONDENCES__FOR_BASHKIR.pdf
