### ISSUE TITLE
Restore GHA workflows for testing and release (was: Need to look into PR #701)

### ISSUE THREAD

**Issue by phuonghuynh** [interscript/interscript-ruby#721]
All release workflows are deleted on "master" for some reasons, we need to get it back and update them all to reflect current site status, i.e. site `-js`, `-api`

Git log command bellow route to this PR contains latest version of release workflow, #701 
```
git log --all --full-history -- "*release.*"
```

/cc @ronaldtse 
/cc @webdev778

**Comment by ronaldtse** [comment]
@webdev778 please have a look, thanks.

**Comment by webdev778** [comment]
Done
[here](https://github.com/interscript/interscript/blob/master/.github/workflows/release.yml)

**Comment by phuonghuynh** [comment]
Thanks @webdev778
