### ISSUE TITLE
List out softwares / libraries need to install for interscrip v2

### ISSUE THREAD

**Issue by phuonghuynh** [interscript/interscript-ruby#723]
As title

/cc @ronaldtse , you could assign this issue to someone that can answers this to help to implement GraphQuery API on AWS Lambda

**Comment by webdev778** [comment]
Please refer [this guide](https://github.com/interscript/interscript/blob/master/docs/Integration_with_Ruby_Applications.adoc)

**Comment by webdev778** [comment]
Hope you check this guide together. 
[Usage with Secryst](https://github.com/interscript/interscript/blob/master/docs/Usage_with_Secryst.adoc)

**Comment by ronaldtse** [comment]
Thanks @webdev778 !

**Comment by phuonghuynh** [comment]
Thanks @webdev778

**Comment by ronaldtse** [comment]
I think we need to provide a sample repository on how to use `Secrystfile` though. Let's create an "interscript demo with secryst"?
