### ISSUE TITLE
Add "stage" for Arabic diacriticization using Rababa

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#735]
The [Rababa gem](https://github.com/interscript/rababa) is used for Arabic script diacriticization.

In order to use Interscript for Arabic transliteration, the text goes through these stages:

1. A text like `قطر` is diacriticized (diacritics added, called the pointed form) into `قِطْرَ`
2. The text of `قِطْرَ` is transliterated by an Arabic map

In reverse transliteration, the following steps:
1. The Arabic transliteration is reversed into a diacriticized Arabic string (pointed Arabic)
2. If desired, the pointed Arabic is dropped into the unpointed form (no diacritics)

We need to implement a stage that allows Arabic diacriticization.

Maybe there needs to be a processing option to do this - user-specified determination of pipeline stages:
* e.g. "diacriticize => bgnpcgn-ara-..."

**Comment by webdev778** [comment]
PR #735
