### ISSUE TITLE
Support multi-line strings for tests

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#736]
Interscript should support multi-line maps instead of forcing a paragraph into a single line.

https://github.com/interscript/maps/blob/f9e197b1a30b0a5710bcbf28df4ac9ade2a05256/maps/alalc-ell-Grek-Latn-1997.imp#L21

From @opoudjis:
> I think it's a shame that the multi-line test at the start is rendered as a continuous string, and not with human-readable line wrapping.

Potentially we can do this:
```
test "Ένα πράμα μόνον με παρακίνησε κι εμένα να γράψω ότι "
  "τούτην την πατρίδα την έχομεν όλοι μαζί, και σοφοί κι αμαθείς "
  "και πλούσιοι και φτωχοί και πολιτικοί και στρατιωτικοί και οι "
  "πλέον μικρότεροι άνθρωποι"
```

_Originally posted by @webdev778 in https://github.com/interscript/interscript/issues/691#issuecomment-799639639_

**Comment by webdev778** [comment]
A syntax of this kind is already supported:

```ruby
test "Ένα πράμα μόνον με παρακίνησε κι εμένα να γράψω ότι " \
  "τούτην την πατρίδα την έχομεν όλοι μαζί, και σοφοί κι αμαθείς " \
  "και πλούσιοι και φτωχοί και πολιτικοί και στρατιωτικοί και οι " \
  "πλέον μικρότεροι άνθρωποι",
       "Latin equivalent"
```

**Comment by ronaldtse** [comment]
Thanks @webdev778 , can we document this in a "Interscript Map Development Reference"?

**Comment by webdev778** [comment]
PR #738
