### ISSUE TITLE
Create Ruby error classes for interscript errors

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#737]
* SystemNotFoundError
* EmptyInputError
* SystemConversionError
* ExceedsLengthLimitError
* ExceedsTimeLimitError

For https://github.com/interscript/interscript-api/issues/21

**Comment by webdev778** [comment]
* ExceedsLengthLimitError
* ExceedsTimeLimitError

Those make sense only for the API. Interscript itself doesn't impose limits.

* EmptyInputError

I have a feeling that this one too.

**Comment by ronaldtse** [comment]
Indeed, let's leave the limits to the API. For the empty input, perhaps it's not even necessary for API.

**Comment by webdev778** [comment]
Done #749
