### ISSUE TITLE
Implement system `alalc-bel-cyrl-latn-1997` (ALA-LC Romanization Table -- Byelorussian (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#74]
This issue is to implement the transliteration system of alalc-bel-cyrl-latn-1997.

This system is referred in the GeoNames database as `bel_Cyrl2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Byelorussian (1997)'.

 Tests should rely on the data extracted for the `bel_Cyrl2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Data: 
[bel_Cyrl2Latn_ALA_1997.csv.zip](https://github.com/riboseinc/interscript/files/4248079/bel_Cyrl2Latn_ALA_1997.csv.zip)

Spec: http://catdir.loc.gov/catdir/cpso/romanization/beloruss.pdf

**Comment by CAMOBAP** [comment]
There is clearly a conflict between zip & pdf, I have marked some of inconsistency

<img width="546" alt="Screen Shot 2020-05-26 at 8 51 46 PM" src="https://user-images.githubusercontent.com/2169738/82954398-4f816b00-9fb5-11ea-81c8-2a424e359b20.png">

<img width="1154" alt="Screen Shot 2020-05-26 at 8 52 06 PM" src="https://user-images.githubusercontent.com/2169738/82954502-92434300-9fb5-11ea-957f-3a66d2265e51.png">

Research in progress...

**Comment by CAMOBAP** [comment]
I have found the table https://img.tyt.by/n/02/d/belorusskiy_translit.jpg which can be used as data

According to it http://catdir.loc.gov/catdir/cpso/romanization/beloruss.pdf - is right but data is wrong

P.S. Looks like data correspond to `BGN/PCGN 1979`

**Comment by CAMOBAP** [comment]
https://en.wikipedia.org/wiki/Combining_character

**Comment by CAMOBAP** [comment]
PR is ready for review https://github.com/interscript/interscript/pull/291

**Comment by ronaldtse** [comment]
@CAMOBAP here we should always follow the spec (PDF) instead of the data.

We will need to run the data to see which ones are wrong and propose changes. Does this mean that all the text in `bel_Cyrl2Latn_ALA_1997` is actually using the system `bgnpcgn-bel-cyrl-latn-1979`?

**Comment by CAMOBAP** [comment]
> here we should always follow the spec (PDF) instead of the data.

@ronaldtse  This is how we are implemented right now

> Does this mean that all the text in bel_Cyrl2Latn_ALA_1997 is actually using the system bgnpcgn-bel-cyrl-latn-1979?

As you may see on my screenshot above 4 rows are ok, I think it's just an accident

I used data from  https://img.tyt.by/n/02/d/belorusskiy_translit.jpg  & https://en.wikipedia.org/wiki/Romanization_of_Belarusian

**Comment by ronaldtse** [comment]
> This is how we are implemented right now

Excellent!

> As you may see on my screenshot above 4 rows are ok, I think it's just an accident

Just to clarify, which of the cases are true?

Case 1. All rows use the `bel_Cyrl2Latn_ALA_1997` system. For the rows outside the 4 rows, the rules for `bel_Cyrl2Latn_ALA_1997` and `bgnpcgn-bel-cyrl-latn-1979` are identical.

Case 2. Only the 4 rows are using `bgnpcgn-bel-cyrl-latn-1979`, the rest are only in `bel_Cyrl2Latn_ALA_1997`.

Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse if we are talking about bel_Cyrl2Latn_ALA_1997.csv.zip 

> Case 1 ...

false

> Case 2

false

----

Data in `bel_Cyrl2Latn_ALA_1997.csv.zip` 100% valid against `bgnpcgn-bel-cyrl-latn-1979` and partially valid against `alalc-bel-cyrl-latn-1997`.

`alalc-bel-cyrl-latn-1997` and `bgnpcgn-bel-cyrl-latn-1979` very similar this is why some rows valid for both

**Comment by ronaldtse** [comment]
Thank you for the clarification! Sounds like the right thing to do is to change all `bel_Cyrl2Latn_ALA_1997` tags into `bgnpcgn-bel-cyrl-latn-1979`.

We should do this analysis for all of the database files. See #226 .
