### ISSUE TITLE
Reverse system run for Arabic diacriticization

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#741]
The reverse of Arabic diacriticization is simply the "dropping of all diacritics" from Arabic.

This function can be accessed in Rababa via this method:

https://github.com/interscript/rababa/blob/9a3588dc3f5eb9a73aca7bb5737d8b1775395795/lib/rababa/diacritizer.rb#L48

We need to:
1. Expose this functionality in the Rababa Interscript map for reverse use
2. Update interscript.org to allow the reverse running of "diacricitized Arabic => Arabic with no diacritics", and the "transliterated Arabic => diacriticized Arabic => Arabic with no diacritics".

**Comment by ronaldtse** [comment]
@webdev778 is this done? Thanks.

**Comment by webdev778** [comment]
Done
