### ISSUE TITLE
Implement system `bgnpcgn-bel-cyrl-latn-1979` (BGN/PCGN Romanization System -- Belarusian (1979)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#75]
This issue is to implement the transliteration system of bgnpcgn-bel-cyrl-latn-1979.

This system is referred in the GeoNames database as `bel_Cyrl2Latn_BGN_1979`, with the system title 'BGN/PCGN Romanization System -- Belarusian (1979)'.

 Tests should rely on the data extracted for the `bel_Cyrl2Latn_BGN_1979` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Data: 
[bel_Cyrl2Latn_BGN_1979.csv.zip](https://github.com/riboseinc/interscript/files/4248078/bel_Cyrl2Latn_BGN_1979.csv.zip)

Spec: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/811510/ROMANIZATION_OF_BELARUSIAN.pdf

**Comment by CAMOBAP** [comment]
Also the spec available on wiki https://ru.wikipedia.org/wiki/%D0%A0%D0%BE%D0%BC%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F_%D0%B1%D0%B5%D0%BB%D0%BE%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0_BGN/PCGN both looks the same

Both Data & Spec looks consistent

**Comment by CAMOBAP** [comment]
PR is ready for review
