### ISSUE TITLE
Implement system `gki-bel-cyrl-latn-1992` (Byelorussian National Cartographic Authority 1992-3 System

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#76]
This issue is to implement the transliteration system of gki-bel-cyrl-latn-1992.

This system is referred in the GeoNames database as `bel_Cyrl2Latn_GBO_1992`, with the system title 'Byelorussian National Cartographic Authority 1992-3 System'.

 Tests should rely on the data extracted for the `bel_Cyrl2Latn_GBO_1992` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Data: 
[bel_Cyrl2Latn_GBO_1992.csv.zip](https://github.com/riboseinc/interscript/files/4248076/bel_Cyrl2Latn_GBO_1992.csv.zip)

**Comment by CAMOBAP** [comment]
I didn't manage to find any spec or even mention of this in any official document in public DB. 

@ronaldtse maybe you have ant clue where to search for it?

**Comment by ronaldtse** [comment]
@CAMOBAP 

It is mentioned here: (1996)
https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/18th-gegn-docs/18th_gegn_WP21.pdf

<img width="901" alt="Screen Shot 2020-05-28 at 3 19 42 AM" src="https://user-images.githubusercontent.com/11865/83063006-13700800-a092-11ea-89eb-cdfa360e8b0e.png">

**Comment by ronaldtse** [comment]
The Academy of Sciences of Belarus system became the 2000, 2007 national system.

**Comment by CAMOBAP** [comment]
Hmm, in this case, every fact says that we should make  "alias" to https://github.com/interscript/interscript/blob/master/maps/by-bel-Cyrl-Latn-2007.yaml

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
I think here it is clear that there was a system based on GOST 1983, by the "Committee of Geodesy of the Council of Ministers", so it differs from the latter systems?

**Comment by CAMOBAP** [comment]
> The Academy of Sciences of Belarus system became the 2000, 2007 national system.

I have missed how `gki-bel-cyrl-latn-1992` related to this

> GOST 1983

`GOST` stands for `GO`vernment `ST`andard, but the number looks unusual for GOST.

I wasn't managed to find GOST with this number. A single GOST which is related to transliteration which I was managed to find is https://en.wikipedia.org/wiki/GOST_16876-71 (can be found here http://tnpa.by/ also)

**Comment by ronaldtse** [comment]
> I have missed how gki-bel-cyrl-latn-1992 related to this

GOST 1983 is actually GOST 16876-71:1983.

The point is the GKI Byelorussian system was created based on GOST 1983, while the current official system was from Academy of Sciences of Belarus. The two systems are from different origins.

I was able to find GOST 1983 here: [7th_UNCSGN_econf.91_3_Add1.html.zip](https://github.com/interscript/interscript/files/4692813/7th_UNCSGN_econf.91_3_Add1.html.zip)
* it is the OCR'ed from this file: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/7th-uncsgn-docs/econf/7th_UNCSGN_econf.91_3_Add1.pdf

Notice that GOST 1983 is listed for "russian". On left side of the table, some rows are labeled `be` -- I believe those indicate rules for the "tailored form of GOST 1983 for Byelorussian".

We should implement this table anyway -- so maybe we should:
1. Implement GOST 16876-71:1983 Russian (`gost-rus-cyrl-latn-16876-71-1983`) (#294)
2. Implement `gki-bel-cyrl-latn-1992` Belarussian by inheriting some rules from `gost-rus-cyrl-latn-16876-71-1983`: adding tailored rules, excluding irrelevant rules. (This system in this ticket, maybe alias to `un-bel-cyrl-latn-1998` as well)
3. Implement GOST 1983 Ukranian by inheriting some rules from `gost-rus-cyrl-latn-16876-71-1983`: adding tailored rules, excluding irrelevant rules. (need some name for this, maybe `un-ukr-cyrl-latn-1998`) (#295)

<img width="515" alt="Screen Shot 2020-05-28 at 9 55 37 AM" src="https://user-images.githubusercontent.com/11865/83090328-1f2bf080-a0cb-11ea-89c7-f918b95aeead.png">
<img width="489" alt="Screen Shot 2020-05-28 at 9 55 48 AM" src="https://user-images.githubusercontent.com/11865/83090332-205d1d80-a0cb-11ea-9fd1-a4bad4956631.png">

<img width="483" alt="Screen Shot 2020-05-28 at 9 59 02 AM" src="https://user-images.githubusercontent.com/11865/83090416-4e426200-a0cb-11ea-9177-dbc365ca3284.png">
<img width="518" alt="Screen Shot 2020-05-28 at 9 57 52 AM" src="https://user-images.githubusercontent.com/11865/83090420-50a4bc00-a0cb-11ea-9983-4cdce3ec62bd.png">

**Comment by CAMOBAP** [comment]
@ronaldtse Thanks for great research, I absolutely agree with the proposed plan

**Comment by CAMOBAP** [comment]
@ronaldtse 
 - https://github.com/interscript/interscript/issues/294 - done
 - There is no information which extra rules should be implemented on top of GOST 1983
 - Data in bel_Cyrl2Latn_GBO_1992.csv.zip doesn't pass validation, maybe because some extra rules not implemented

**Comment by ronaldtse** [comment]
> There is no information which extra rules should be implemented on top of GOST 1983

Got it. We'll keep it as is now.

> Data in bel_Cyrl2Latn_GBO_1992.csv.zip doesn't pass validation, maybe because some extra rules not implemented

It is possible that those data match another Belarussian system instead -- maybe bel_Cyrl2Latn_BGN_1979 ?

**Comment by ronaldtse** [comment]
Done in #297
