### ISSUE TITLE
Implement system `by-bel-cyrl-latn-1998` (Byelorussian Government of Belarus 1998 System

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#77]
This issue is to implement the transliteration system of by-bel-cyrl-latn-1998.

This system is referred in the GeoNames database as `bel_Cyrl2Latn_GBO_1998`, with the system title 'Byelorussian Government of Belarus 1998 System'.

 Tests should rely on the data extracted for the `bel_Cyrl2Latn_GBO_1998` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Data: 
[bel_Cyrl2Latn_GBO_1998.csv.zip](https://github.com/riboseinc/interscript/files/4248077/bel_Cyrl2Latn_GBO_1998.csv.zip)

History: (https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/8th-uncsgn-docs/crp/8th_UNCSGN_econf.94_crp.80.pdf)
> A new national system of romanization for Byelorussian was approved by the Government Committee on Land Resources, Geodesy and Cartography, Republic of Belarus, on 23 November 2000, modifying an earlier system of 1998. The system is based on GOST 1983, taking into account the peculiarities of the Byelorussian orthography.

**Comment by ronaldtse** [comment]
Spec: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/20th-gegn-docs/20th_gegn_WP34.pdf
<img width="1081" alt="Screen Shot 2020-02-25 at 1 05 04 PM" src="https://user-images.githubusercontent.com/11865/75216582-715d2d00-57cf-11ea-8d22-2ea5783802a7.png">
<img width="1077" alt="Screen Shot 2020-02-25 at 1 05 11 PM" src="https://user-images.githubusercontent.com/11865/75216590-75894a80-57cf-11ea-92b2-364503a8c886.png">

**Comment by CAMOBAP** [comment]
Data in bel_Cyrl2Latn_GBO_1998.csv.zip actually correspond to BGN/PCGN, this romanization table are the same as was in by-bel-Cyrl-Latn-2007 so I will make alias

**Comment by CAMOBAP** [comment]
PR is ready for review https://github.com/interscript/interscript/pull/292
