### ISSUE TITLE
Implement system `alalc-ben-beng-latn-1997` (ALA-LC Romanization Table -- Bengali (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#78]
This issue is to implement the transliteration system of alalc-ben-beng-latn-1997.

This system is referred in the GeoNames database as `ben_Beng2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Bengali (1997)'.

 Tests should rely on the data extracted for the `ben_Beng2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
@ronaldtse PR: https://github.com/interscript/interscript/pull/611
