### ISSUE TITLE
Implement system `alalc-bul-cyrl-latn-1997` (ALA-LC Romanization Table -- Bulgarian (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#80]
This issue is to implement the transliteration system of alalc-bul-cyrl-latn-1997.

This system is referred in the GeoNames database as `bul_Cyrl2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Bulgarian (1997)'.

 Tests should rely on the data extracted for the `bul_Cyrl2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
Cannot find samples in https://github.com/riboseinc/geonames-transliteration-data
