### ISSUE TITLE
Implement system `bgnpcgn-bul-cyrl-latn-1952` (BGN/PCGN Romanization System -- Bulgarian (1952)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#81]
This issue is to implement the transliteration system of bgnpcgn-bul-cyrl-latn-1952.

This system is referred in the GeoNames database as `bul_Cyrl2Latn_BGN_1952`, with the system title 'BGN/PCGN Romanization System -- Bulgarian (1952)'.

 Tests should rely on the data extracted for the `bul_Cyrl2Latn_BGN_1952` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
Ready to review #299
