### ISSUE TITLE
Implement system `bgnpcgn-bul-cyrl-latn-2013` (BGN/PCGN Romanization Agreement -- Bulgarian (2013)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#82]
This issue is to implement the transliteration system of bgnpcgn-bul-cyrl-latn-2013.

This system is referred in the GeoNames database as `bul_Cyrl2Latn_BGN_2013`, with the system title 'BGN/PCGN Romanization Agreement -- Bulgarian (2013)'.

 Tests should rely on the data extracted for the `bul_Cyrl2Latn_BGN_2013` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
As far as I see it's already done https://github.com/interscript/interscript/commit/f43dacf9b55f5ce3eb7bcc3e8bab4f415e0ed2ff#diff-49108f3250c35505e4f42a39d8ac5a9c, I will modify it a bit in the scope of #81 (inherit from 1952)

@ronaldtse am I right?

**Comment by CAMOBAP** [comment]
Done
