### ISSUE TITLE
Implement system `bgna-bul-cyrl-latn-2006` (Bulgarian National Assembly Romanization 2006)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#83]
This issue is to implement the transliteration system of `bgna-bul-cyrl-latn-2006`.

~~This system is referred in the GeoNames database as `bul_Cyrl2Latn_BUL_1952` (but it refers to 2002!), with the system title 'Bulgarian 2002 Bulgarian Government Romanization System' (but the system was adopted in 2006!).~~

~~There is currently no data of the `bul_Cyrl2Latn_BUL_1952` system in https://github.com/riboseinc/geonames-transliteration-data .~~

Luckily this is just an 100% inherited system from `apcbg-bul-cyrl-latn-1995` (#256)

```
bgna-bul-cyrl-latn-2006,Republic of Bulgaria system for transliteration of Bulgarian geographical names with Roman letters,bgna,iso-639-2,bul,Cyrl,Latn,2006,<<BulLatUN2006>>,adoptedFrom:apcbg-bul-cyrl-latn-1995,Date adopted: 2006-10-26
```

**Comment by CAMOBAP** [comment]
Ready to review #299

**Comment by CAMOBAP** [comment]
Done
