### ISSUE TITLE
Implement system `odni-bul-cyrl-latn-2005` (Office of the Director Of National Intelligence Bulgarian Personal Names 2004 System

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#84]
This issue is to implement the transliteration system of odni-bul-cyrl-latn-2005.

This system is referred in the GeoNames database as `bul_Cyrl2Latn_ODNI_2005`, with the system title 'Office of the Director Of National Intelligence Bulgarian Personal Names 2004 System'.

 Tests should rely on the data extracted for the `bul_Cyrl2Latn_ODNI_2005` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
@ronaldtse Maybe you have an idea where to find spec? Also, there is no test data

**Comment by ronaldtse** [comment]
https://github.com/interscript/ics-630-01/blob/master/reference-docs/ANNEX%20O%20-%20Bulgarian_Person-Name_IC_Standard_FLTS%20(U).pdf

Unfortunately there is no test data... we need to make some up.

**Comment by CAMOBAP** [comment]
@ronaldtse the doc above refers to 2009 and 2013 years and I sure that it's related to https://github.com/interscript/interscript/issues/272

So we still have no spec for this one

**Comment by ronaldtse** [comment]
Yes you're right. Let me ask for the spec, but could we link this test data with the #272 systems for now? Maybe they would already suit this system?

**Comment by ronaldtse** [comment]
We're going to skip all non-current ODNI systems for now. Closing this for now. Thanks!

**Comment by ronaldtse** [comment]
Spec available now: https://github.com/interscript/interscript-private-references/blob/master/odni/Bulgarian_IC_Standard.doc

**Comment by ronaldtse** [comment]
Merged in #650 . Thanks @CAMOBAP !
