### ISSUE TITLE
Implement system `bgnpcgn-che-cyrl-latn-2007` (BGN/PCGN Table of Correspondences -- Chechen (2007)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#85]
This issue is to implement the transliteration system of bgnpcgn-che-cyrl-latn-2007.

This system is referred in the GeoNames database as `che_Cyrl2Latn_BGN_2007`, with the system title 'BGN/PCGN Table of Correspondences -- Chechen (2007)'.

 Tests should rely on the data extracted for the `che_Cyrl2Latn_BGN_2007` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by CAMOBAP** [comment]
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/835782/TABLE_OF_CORRESPONDENCES_FOR_CHECHEN.pdf

**Comment by ronaldtse** [comment]
Merged in #543.
