### ISSUE TITLE
Implement system `alalc-div-thaa-latn-1997` (ALA-LC Romanization Table -- Maldivian (Divehi) (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#87]
This issue is to implement the transliteration system of alalc-div-thaa-latn-1997.

This system is referred in the GeoNames database as `div_Thaa2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Maldivian (Divehi) (1997)'.

 Tests should rely on the data extracted for the `div_Thaa2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
@ronaldtse PR: https://github.com/interscript/interscript/pull/644

**Comment by bilashsaha** [comment]
@ronaldtse PR: https://github.com/interscript/interscript/pull/645

**Comment by ronaldtse** [comment]
Thanks @bilashsaha!
