### ISSUE TITLE
Implement system `bgnpcgn-div-thaa-latn-1972` (BGN/PCGN Romanization System -- Maldivian (Divehi) (1972)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#88]
This issue is to implement the transliteration system of bgnpcgn-div-thaa-latn-1972.

This system is referred in the GeoNames database as `div_Thaa2Latn_BGN_1972`, with the system title 'BGN/PCGN Romanization System -- Maldivian (Divehi) (1972)'.

 Tests should rely on the data extracted for the `div_Thaa2Latn_BGN_1972` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
@ronaldtse I had implemented `bgnpcgn-div-Thaa-Latn-1988` at https://github.com/interscript/interscript/pull/649. From the [documentation](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/816778/ROMANIZATION_OF_MALDIVIAN.pdf) it says this system supersedes the one that was approved by BGN and PCGN in 1972. I did not find any documentation for BGN and PCGN in 1972. Should `bgnpcgn-div-Thaa-Latn-1988` fix this one ?

**Comment by bilashsaha** [comment]
closing this with https://github.com/interscript/interscript/pull/649

**Comment by ronaldtse** [comment]
Actually let’s keep this open for now, will find out the 1972 version.

**Comment by ronaldtse** [comment]
@bilashsaha we've received the 1972 version from BGN (thanks!) This is ready to be implemented 👍 

![bgnpcgn-maldivian-1972](https://user-images.githubusercontent.com/11865/101876181-f8e12480-3bc6-11eb-8679-c328a7c35ddf.jpg)

**Comment by bilashsaha** [comment]
@ronaldtse PR: https://github.com/interscript/interscript/pull/688

**Comment by ronaldtse** [comment]
All done. Thanks @bilashsaha !
