### ISSUE TITLE
Implement system `mv-div-thaa-latn-1987` (Maldivian (Divehi) Maldivian Government 1987 system

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#89]
This issue is to implement the transliteration system of mv-div-thaa-latn-1987.

This system is referred in the GeoNames database as `div_Thaa2Latn_GMV_1988`, with the system title 'Maldivian (Divehi) Maldivian Government 1988 system'.

 Tests should rely on the data extracted for the `div_Thaa2Latn_GMV_1988` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by bilashsaha** [comment]
@ronaldtse I did not find any reference document for this system. The [documentation](https://geonames.nga.mil/gns/html/Romanization/ROMANIZATION%20OF%20MALDIVIAN.pdf) says that `An official system was submitted to PCGN by the Maldivian government in 1987 and approved by BGN and PCGN in 1988` Should we follow this for this system ?

Also I think the [UN romanization for Maldivian](https://www.eki.ee/wgrs/rom2_dv.htm) points out the Maldivian Government system. As per their note in this page.

**Comment by ronaldtse** [comment]
@bilashsaha agree that https://www.eki.ee/wgrs/rom2_dv.htm is the spec for the Maldivian Government System. And it's apparently 1987 not 1988. 1988 seems to be the date adopted by BGN/PCGN, which is different.

If the Government and the BGN systems are identical, we should make BGN inherit from the Government one.

**Comment by bilashsaha** [comment]
@ronaldtse Government and the BGN systems are not fully identical. I am implementing the rules separately.

**Comment by bilashsaha** [comment]
@ronaldtse PR: https://github.com/interscript/interscript/pull/651
