### ISSUE TITLE
Add UN Russian Romanization system

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#9]
The first system on http://www.eki.ee/wgrs/rom1_ru.htm .

i.e. 

Russian

The United Nations recommended system was approved in 1987 (V/18), based on the official system of the Main Administration of Geodesy and Cartography of the former Soviet Union, also known as the GOST 1983 system (GOST 16876-71). The table was published as an annex to the resolution1.

The system is used in the Russian Federation and increasingly in international cartographic products.

Russian uses the Cyrillic script which is alphabetic. The romanization table is unambiguous and can be applied automatically. The system is reversible, although rarely there can be ambiguities. For example, a geographical name Bajuba is reconstituted as Байуба in the Cyrillic source script, not Баюба as might be expected.

Romanization

1 | А а | a
-- | -- | --
2 | Б б | b
3 | В в | v
4 | Г г | g
5 | Д д | d
6 | Е е | e
7 | Ё ё | ë
8 | Ж ж | ž
9 | З з | z
10 | И и | i
11 | Й й | j
12 | К к | k
13 | Л л | l
14 | М м | m
15 | Н н | n
16 | О о | o
17 | П п | p
18 | Р р | r
19 | С с | s
20 | Т т | t
21 | У у | u
22 | Ф ф | f
23 | Х х | h
24 | Ц ц | c
25 | Ч ч | č
26 | Ш ш | š
27 | Щ щ | šč
28 | Ъ ъ | "
29 | Ы ы | y
30 | Ь ь | ’
31 | Э э | è
32 | Ю ю | ju
33 | Я я | ja

Note. Cursive forms of some characters might be formed differently: Аа Бб Вв Гг Дд Ее Ёё Жж Зз Ии Йй Кк Лл Мм Нн Оо Пп Рр Сс Тт Уу Фф Хх Цц Чч Шш Щщ Ъъ Ыы Ьь Ээ Юю Яя.

References

Fifth United Nations Conference on the Standardization of Geographical Names. Montreal, 18–31 August 1987. Vol. I. Report of the Conference, pp. 40–41.

**Comment by manuelfuenmayor** [comment]
Hi Ron,
Two questions:
1. Regarding rows 28 and 30, would the proper mapping be something like this:
	`'\u042A' : '\u016c'  # Ъ`
	`'\u044A' : '\u016c'  # ъ` 

	`'\u042C' : "\'" # Ь`
	`'\u044C' : "\'"  # ь`

2. Should I add the reference part as a note?

**Comment by ronaldtse** [comment]
1. It should be:

```
'\u042C' : '"' # Ь
'\u044C' : '"' # ь
```

2. Please do so. Thanks!

**Comment by ronaldtse** [comment]
Original text from: https://unstats.un.org/unsd/geoinfo/ungegn/docs/5th-uncsgn-doc/5-uncsgn-rpt-en.pdf

<img width="796" alt="Screen Shot 2019-11-19 at 12 35 06 AM" src="https://user-images.githubusercontent.com/11865/69071297-a20d2800-0a64-11ea-8f5b-5b475a193136.png">

<img width="811" alt="Screen Shot 2019-11-19 at 12 34 53 AM" src="https://user-images.githubusercontent.com/11865/69071285-9883c000-0a64-11ea-8a06-3d4bcac3a446.png">

**Comment by manuelfuenmayor** [comment]
@ronaldtse. Roughly, how many  examples (or tests) should be fine to add? In the capture you shared, there are like 40 examples. Should I add them all?

**Comment by manuelfuenmayor** [comment]
> 1. It should be:
> 
> ```
> '\u042C' : '"' # Ь
> '\u044C' : '"' # ь
> ```
> 
> 2. Please do so. Thanks!

In point 1, you added the correspoding map for row 30, right? What about row 28?

**Comment by ronaldtse** [comment]
Thanks @manuel489 !
