### ISSUE TITLE
Implement system `alalc-ell-grek-latn-1997` (ALA-LC Romanization Table -- Greek (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#91]
This issue is to implement the transliteration system of alalc-ell-grek-latn-1997.

This system is referred in the GeoNames database as `ell_Grek2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Greek (1997)'.

~~Tests should rely on the data extracted for the `ell_Grek2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .~~ There is actually no data entered using this system in GNDB.

**Comment by ronaldtse** [comment]
Spec:
* https://www.loc.gov/catdir/cpso/romanization/greek.pdf
* https://www.geisteswissenschaften.fu-berlin.de/we02/griechisch/neograezistik/bibliothek/philologische-bibliothek/greek_translit_kon.pdf

**Comment by ronaldtse** [comment]
Test data: need to be found.

**Comment by opoudjis** [comment]
Need to also implement 2010 mapping:

https://www.loc.gov/catdir/cpso/romanization/greek.pdf

1997 is http://catdir.loc.gov/catdir/cpso/romanization/greek.pdf
