### ISSUE TITLE
Implement system `alalc-per-arab-latn-1997` (ALA-LC Romanization Table -- Persian (1997)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#94]
This issue is to implement the transliteration system of alalc-per-arab-latn-1997.

This system is referred in the GeoNames database as `fas_Arab2Latn_ALA_1997`, with the system title 'ALA-LC Romanization Table -- Persian (1997)'.

 Tests should rely on the data extracted for the `fas_Arab2Latn_ALA_1997` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
Spec: http://catdir.loc.gov/catdir/cpso/romanization/persian.pdf

**Comment by AhMohsen46** [comment]
Thanks @ronaldtse , getting this done now

**Comment by AhMohsen46** [comment]
built here https://github.com/interscript/interscript/pull/544
will create an issue for questions, this can be closed
