### ISSUE TITLE
Implement system `bgnpcgn-per-arab-latn-1958` (BGN/PCGN Romanization System -- Persian (1958)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#96]
This issue is to implement the transliteration system of bgnpcgn-per-arab-latn-1958.

This system is referred in the GeoNames database as `fas_Arab2Latn_BGN_1958`, with the system title 'BGN/PCGN Romanization System -- Persian (1958)'.

 Tests should rely on the data extracted for the `fas_Arab2Latn_BGN_1958` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
[BGN_Romanization_Guide_1964_persian_1958.pdf](https://github.com/interscript/interscript/files/5180821/BGN_Romanization_Guide_1964_persian_1958.pdf)

**Comment by AhMohsen46** [comment]
Done in https://github.com/interscript/interscript/pull/511
