### ISSUE TITLE
Implement system `odni-per-arab-latn-2004` (Office of the Director Of National Intelligence Farsi (Iranian Persian) Personal Names 2004 System

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#98]
This issue is to implement the transliteration system of odni-per-arab-latn-2004.

This system is referred in the GeoNames database as `fas_Arab2Latn_ODNI_2004`, with the system title 'Office of the Director Of National Intelligence Farsi (Iranian Persian) Personal Names 2004 System'.

 Tests should rely on the data extracted for the `fas_Arab2Latn_ODNI_2004` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by AhMohsen46** [comment]
@ronaldtse is there any document for this fas_Arab2Latn_ODNI_2004 ?

**Comment by ronaldtse** [comment]
I will find spec, please hold this for now.

**Comment by AhMohsen46** [comment]
any updates on this doc?

**Comment by ronaldtse** [comment]
We're going to skip all non-current ODNI systems for now. Closing this for now. Thanks!

**Comment by ronaldtse** [comment]
Spec: https://github.com/interscript/interscript-private-references/blob/master/odni/Farsi_(Persian)_%26_Dari_IC_Standards.doc

The spec includes both Farsi and Dari. Dari should be a separate system.

**Comment by AhMohsen46** [comment]
Done in #623, both systems
they are like 99% similar to #510
concerns are the exact same as #509
Thanks!
